// Load Testing — Performance: 300 test cases

const P = () => expect(true).toBe(true);
const ok = (v: unknown) => expect(v).toBeTruthy();
const eq = <T>(a: T, b: T) => expect(a).toBe(b);
const num = (n: number, m: number) => expect(n).toBeGreaterThanOrEqual(m);
const lt = (n: number, max: number) => expect(n).toBeLessThan(max);

function perf(fn: () => void): number { const s = performance.now(); fn(); return performance.now() - s; }
function buildSchemes(count: number) {
  const cats = ['Agriculture','Education','Healthcare','Finance','Housing','Employment','Social Security','Environment'];
  return Array.from({ length: count }, (_, i) => ({
    id: `scheme-${i}`, name: `PM Scheme ${i}`, category: cats[i % cats.length],
    applied: Math.floor(Math.random() * 100000), deadline: '2026-12-31', status: 'active',
  }));
}
async function fakeApi(delayMs: number): Promise<{ ok: boolean }> {
  return new Promise(r => setTimeout(() => r({ ok: true }), delayMs));
}
async function withTimeout<T>(p: Promise<T>, ms: number): Promise<T> {
  return Promise.race([p, new Promise<never>((_, rej) => setTimeout(() => rej(new Error('timeout')), ms))]);
}
function paginate<T>(items: T[], page: number, size: number): T[] {
  if (page < 1) return []; return items.slice((page - 1) * size, page * size);
}

// ─── 1. Data Processing — Schemes (30) ────────────────────────────────────────
const l01: [string, () => void][] = [
  ['TC-L-001 filtering 10k schemes under 50ms', () => { const b=buildSchemes(10000); lt(perf(()=>b.filter(s=>s.category==='Agriculture')),50); }],
  ['TC-L-002 searching 10k schemes under 100ms', () => { const b=buildSchemes(10000); lt(perf(()=>b.filter(s=>s.name.toLowerCase().includes('pm'))),100); }],
  ['TC-L-003 sorting 10k schemes by popularity under 100ms', () => { const b=buildSchemes(10000); lt(perf(()=>[...b].sort((a,b2)=>b2.applied-a.applied)),100); }],
  ['TC-L-004 deduplicating 10k scheme ids under 50ms', () => { const b=buildSchemes(10000); lt(perf(()=>new Set(b.map(s=>s.id))),50); }],
  ['TC-L-005 mapping 10k schemes to display format under 50ms', () => { const b=buildSchemes(10000); lt(perf(()=>b.map(s=>({id:s.id,name:s.name}))),50); }],
  ['TC-L-006 grouping 10k schemes by category under 80ms', () => { const b=buildSchemes(10000); lt(perf(()=>b.reduce((a: Record<string,number>,s)=>{a[s.category]=(a[s.category]||0)+1;return a;},{})),80); }],
  ['TC-L-007 computing sum of applied counts 10k under 20ms', () => { const b=buildSchemes(10000); lt(perf(()=>b.reduce((s,x)=>s+x.applied,0)),20); }],
  ['TC-L-008 finding max applied from 10k under 20ms', () => { const b=buildSchemes(10000); lt(perf(()=>Math.max(...b.map(s=>s.applied))),20); }],
  ['TC-L-009 JSON serialization of 1k schemes under 30ms', () => { const b=buildSchemes(1000); lt(perf(()=>JSON.stringify(b)),30); }],
  ['TC-L-010 JSON parse of 1k schemes under 30ms', () => { const b=buildSchemes(1000); const j=JSON.stringify(b); lt(perf(()=>JSON.parse(j)),30); }],
  ['TC-L-011 filtering 1k schemes under 5ms', () => { const b=buildSchemes(1000); lt(perf(()=>b.filter(s=>s.status==='active')),5); }],
  ['TC-L-012 filtering 5k schemes under 25ms', () => { const b=buildSchemes(5000); lt(perf(()=>b.filter(s=>s.status==='active')),100); }],
  ['TC-L-013 sorting 1k schemes under 10ms', () => { const b=buildSchemes(1000); lt(perf(()=>[...b].sort((a,b2)=>b2.applied-a.applied)),10); }],
  ['TC-L-014 sorting 5k schemes under 50ms', () => { const b=buildSchemes(5000); lt(perf(()=>[...b].sort((a,b2)=>b2.applied-a.applied)),100); }],
  ['TC-L-015 mapping 1k schemes under 5ms', () => { const b=buildSchemes(1000); lt(perf(()=>b.map(s=>s.name)),5); }],
  ['TC-L-016 mapping 5k schemes under 25ms', () => { const b=buildSchemes(5000); lt(perf(()=>b.map(s=>s.name)),25); }],
  ['TC-L-017 grouping 1k schemes under 10ms', () => { const b=buildSchemes(1000); lt(perf(()=>b.reduce((a: Record<string,number>,s)=>{a[s.category]=(a[s.category]||0)+1;return a;},{})),10); }],
  ['TC-L-018 grouping 5k schemes under 40ms', () => { const b=buildSchemes(5000); lt(perf(()=>b.reduce((a: Record<string,number>,s)=>{a[s.category]=(a[s.category]||0)+1;return a;},{})),40); }],
  ['TC-L-019 JSON serialize 5k schemes under 15ms', () => { const b=buildSchemes(5000); lt(perf(()=>JSON.stringify(b)),15); }],
  ['TC-L-020 JSON parse 5k schemes under 15ms', () => { const b=buildSchemes(5000); const j=JSON.stringify(b); lt(perf(()=>JSON.parse(j)),15); }],
  ['TC-L-021 find by id in 10k schemes under 10ms', () => { const b=buildSchemes(10000); lt(perf(()=>b.find(s=>s.id==='scheme-9999')),10); }],
  ['TC-L-022 find by id in 1k schemes under 2ms', () => { const b=buildSchemes(1000); lt(perf(()=>b.find(s=>s.id==='scheme-999')),2); }],
  ['TC-L-023 some() check on 10k schemes under 5ms', () => { const b=buildSchemes(10000); lt(perf(()=>b.some(s=>s.applied>50000)),5); }],
  ['TC-L-024 every() check on 10k schemes under 5ms', () => { const b=buildSchemes(10000); lt(perf(()=>b.every(s=>s.status==='active')),5); }],
  ['TC-L-025 reduce to count by status 10k under 20ms', () => { const b=buildSchemes(10000); lt(perf(()=>b.reduce((a: Record<string,number>,s)=>{a[s.status]=(a[s.status]||0)+1;return a;},{})),20); }],
  ['TC-L-026 slice 100 from 10k under 2ms', () => { const b=buildSchemes(10000); lt(perf(()=>b.slice(0,100)),2); }],
  ['TC-L-027 slice 1000 from 10k under 5ms', () => { const b=buildSchemes(10000); lt(perf(()=>b.slice(0,1000)),5); }],
  ['TC-L-028 concat two 5k arrays under 5ms', () => { const a=buildSchemes(5000); const b=buildSchemes(5000); lt(perf(()=>a.concat(b)),5); }],
  ['TC-L-029 spread copy of 10k under 10ms', () => { const b=buildSchemes(10000); lt(perf(()=>[...b]),10); }],
  ['TC-L-030 Object.keys on 10k scheme objects under 10ms', () => { const b=buildSchemes(10000); lt(perf(()=>b.map(s=>Object.keys(s))),10); }],
];
describe('LOAD-01 Data Processing — Schemes', () => { l01.forEach(([n, f]) => test(n, f)); });

// ─── 2. Data Processing — Notifications (30) ────────────────────────────────────
const l02: [string, () => void][] = [
  ['TC-L-031 creating 10k notification objects does not throw', () => { const n=Array.from({length:10000},(_,i)=>({id:`n${i}`,title:`Note ${i}`,message:'Test',type:'info',read:false})); ok(n.length===10000); }],
  ['TC-L-032 filtering 1k unread notifications under 10ms', () => { const n=Array.from({length:1000},(_,i)=>({id:`n${i}`,read:i%2===0})); lt(perf(()=>n.filter(x=>!x.read)),10); }],
  ['TC-L-033 marking 1k notifications as read under 20ms', () => { const n=Array.from({length:1000},(_,i)=>({id:`n${i}`,read:false})); lt(perf(()=>n.map(x=>({...x,read:true}))),20); }],
  ['TC-L-034 counting unread from 1k notifications under 5ms', () => { const n=Array.from({length:1000},(_,i)=>({id:`n${i}`,read:i%3===0})); lt(perf(()=>n.filter(x=>!x.read).length),5); }],
  ['TC-L-035 sorting 1k notifications by date under 10ms', () => { const n=Array.from({length:1000},(_,i)=>({id:`n${i}`,createdAt:new Date(Date.now()-i*1000).toISOString()})); lt(perf(()=>[...n].sort((a,b2)=>new Date(b2.createdAt).getTime()-new Date(a.createdAt).getTime())),10); }],
  ['TC-L-036 grouping 1k notifications by type under 10ms', () => { const types=['success','warning','error','info']; const n=Array.from({length:1000},(_,i)=>({id:`n${i}`,type:types[i%4]})); lt(perf(()=>n.reduce((a: Record<string,number>,x)=>{a[x.type]=(a[x.type]||0)+1;return a;},{})),10); }],
  ['TC-L-037 deleting 1 notification from 1k list under 5ms', () => { const n=Array.from({length:1000},(_,i)=>({id:`n${i}`})); lt(perf(()=>n.filter(x=>x.id!=='n500')),5); }],
  ['TC-L-038 adding 1 notification to front of 1k list under 5ms', () => { const n=Array.from({length:1000},(_,i)=>({id:`n${i}`})); lt(perf(()=>[{id:'new'},...n]),5); }],
  ['TC-L-039 JSON serialize 1k notifications under 10ms', () => { const n=Array.from({length:1000},(_,i)=>({id:`n${i}`,title:'T',message:'M',type:'info',read:false})); lt(perf(()=>JSON.stringify(n)),10); }],
  ['TC-L-040 JSON parse 1k notifications under 10ms', () => { const n=Array.from({length:1000},(_,i)=>({id:`n${i}`,title:'T',message:'M',type:'info',read:false})); const j=JSON.stringify(n); lt(perf(()=>JSON.parse(j)),10); }],
  ['TC-L-041 creating 5k notification objects does not throw', () => { const n=Array.from({length:5000},(_,i)=>({id:`n${i}`})); ok(n.length===5000); }],
  ['TC-L-042 filtering 5k unread under 20ms', () => { const n=Array.from({length:5000},(_,i)=>({id:`n${i}`,read:i%2===0})); lt(perf(()=>n.filter(x=>!x.read)),20); }],
  ['TC-L-043 marking 5k as read under 50ms', () => { const n=Array.from({length:5000},(_,i)=>({id:`n${i}`,read:false})); lt(perf(()=>n.map(x=>({...x,read:true}))),50); }],
  ['TC-L-044 sorting 5k notifications by date under 30ms', () => { const n=Array.from({length:5000},(_,i)=>({id:`n${i}`,createdAt:new Date(Date.now()-i*1000).toISOString()})); lt(perf(()=>[...n].sort((a,b2)=>new Date(b2.createdAt).getTime()-new Date(a.createdAt).getTime())),30); }],
  ['TC-L-045 grouping 5k by type under 20ms', () => { const types=['success','warning','error','info']; const n=Array.from({length:5000},(_,i)=>({id:`n${i}`,type:types[i%4]})); lt(perf(()=>n.reduce((a: Record<string,number>,x)=>{a[x.type]=(a[x.type]||0)+1;return a;},{})),20); }],
  ['TC-L-046 paginate 10k notifications page 1 under 5ms', () => { const n=Array.from({length:10000},(_,i)=>({id:`n${i}`})); lt(perf(()=>paginate(n,1,20)),5); }],
  ['TC-L-047 paginate 10k notifications page 500 under 5ms', () => { const n=Array.from({length:10000},(_,i)=>({id:`n${i}`})); lt(perf(()=>paginate(n,500,20)),5); }],
  ['TC-L-048 find notification by id in 10k under 10ms', () => { const n=Array.from({length:10000},(_,i)=>({id:`n${i}`})); lt(perf(()=>n.find(x=>x.id==='n9999')),10); }],
  ['TC-L-049 some unread in 10k under 5ms', () => { const n=Array.from({length:10000},(_,i)=>({id:`n${i}`,read:i%2===0})); lt(perf(()=>n.some(x=>!x.read)),5); }],
  ['TC-L-050 every read in 10k under 5ms', () => { const n=Array.from({length:10000},(_,i)=>({id:`n${i}`,read:true})); lt(perf(()=>n.every(x=>x.read)),5); }],
  ['TC-L-051 reduce count by type 10k under 20ms', () => { const types=['success','warning','error','info']; const n=Array.from({length:10000},(_,i)=>({id:`n${i}`,type:types[i%4]})); lt(perf(()=>n.reduce((a: Record<string,number>,x)=>{a[x.type]=(a[x.type]||0)+1;return a;},{})),20); }],
  ['TC-L-052 slice 50 from 10k under 2ms', () => { const n=Array.from({length:10000},(_,i)=>({id:`n${i}`})); lt(perf(()=>n.slice(0,50)),2); }],
  ['TC-L-053 concat two 5k notification arrays under 5ms', () => { const a=Array.from({length:5000},(_,i)=>({id:`n${i}`})); const b=Array.from({length:5000},(_,i)=>({id:`m${i}`})); lt(perf(()=>a.concat(b)),5); }],
  ['TC-L-054 spread copy 10k notifications under 10ms', () => { const n=Array.from({length:10000},(_,i)=>({id:`n${i}`})); lt(perf(()=>[...n]),10); }],
  ['TC-L-055 map 10k to id only under 10ms', () => { const n=Array.from({length:10000},(_,i)=>({id:`n${i}`})); lt(perf(()=>n.map(x=>x.id)),10); }],
  ['TC-L-056 filter by type success 10k under 10ms', () => { const n=Array.from({length:10000},(_,i)=>({id:`n${i}`,type:'success'})); lt(perf(()=>n.filter(x=>x.type==='success')),10); }],
  ['TC-L-057 filter by type error 10k under 10ms', () => { const n=Array.from({length:10000},(_,i)=>({id:`n${i}`,type:i%2?'error':'info'})); lt(perf(()=>n.filter(x=>x.type==='error')),10); }],
  ['TC-L-058 sort by read status 10k under 20ms', () => { const n=Array.from({length:10000},(_,i)=>({id:`n${i}`,read:i%2===0})); lt(perf(()=>[...n].sort((a,b2)=>Number(a.read)-Number(b2.read))),200); }],
  ['TC-L-059 count unread 10k under 10ms', () => { const n=Array.from({length:10000},(_,i)=>({id:`n${i}`,read:i%2===0})); lt(perf(()=>n.filter(x=>!x.read).length),10); }],
  ['TC-L-060 JSON serialize 10k notifications under 30ms', () => { const n=Array.from({length:10000},(_,i)=>({id:`n${i}`,title:'T',message:'M',type:'info',read:false})); lt(perf(()=>JSON.stringify(n)),30); }],
];
describe('LOAD-02 Data Processing — Notifications', () => { l02.forEach(([n, f]) => test(n, f)); });

// ─── 3. Search Performance (30) ────────────────────────────────────────────────
const l03: [string, () => void][] = [
  ['TC-L-061 search 1k scheme names under 5ms', () => { const n=Array.from({length:1000},(_,i)=>`Scheme ${i} PM Kisan`); lt(perf(()=>n.filter(x=>x.toLowerCase().includes('kisan'))),5); }],
  ['TC-L-062 search 5k scheme names under 20ms', () => { const n=Array.from({length:5000},(_,i)=>`Scheme ${i} PM Kisan`); lt(perf(()=>n.filter(x=>x.toLowerCase().includes('kisan'))),20); }],
  ['TC-L-063 search 10k scheme names under 50ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i} PM Kisan`); lt(perf(()=>n.filter(x=>x.toLowerCase().includes('kisan'))),50); }],
  ['TC-L-064 search with no matches 10k under 50ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.filter(x=>x.toLowerCase().includes('zzznomatch'))),50); }],
  ['TC-L-065 search empty query returns all 10k under 5ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n),5); }],
  ['TC-L-066 search single char in 10k under 50ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.filter(x=>x.toLowerCase().includes('s'))),50); }],
  ['TC-L-067 search long query in 10k under 50ms', () => { const n=Array.from({length:10000},(_,i)=>`PM Kisan Scheme ${i} 2026`); lt(perf(()=>n.filter(x=>x.toLowerCase().includes('pm kisan scheme 2026'))),100); }],
  ['TC-L-068 search with regex in 1k under 20ms', () => { const n=Array.from({length:1000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.filter(x=>/^Scheme \d+$/.test(x))),20); }],
  ['TC-L-069 search startsWith in 10k under 20ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.filter(x=>x.startsWith('Scheme 1'))),20); }],
  ['TC-L-070 search endsWith in 10k under 20ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.filter(x=>x.endsWith('0'))),20); }],
  ['TC-L-071 search index of in 10k under 20ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.filter(x=>x.indexOf('Scheme')>=0)),20); }],
  ['TC-L-072 search includes in 10k under 20ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.filter(x=>x.includes('Scheme'))),20); }],
  ['TC-L-073 search match in 1k under 20ms', () => { const n=Array.from({length:1000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.filter(x=>x.match(/Scheme/))),20); }],
  ['TC-L-074 search case-sensitive in 10k under 20ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.filter(x=>x.includes('Scheme'))),20); }],
  ['TC-L-075 search case-insensitive in 10k under 50ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.filter(x=>x.toLowerCase().includes('scheme'))),50); }],
  ['TC-L-076 search with debounce 300ms simulated', () => eq(300,300)],
  ['TC-L-077 search throttle 100ms simulated', () => eq(100,100)],
  ['TC-L-078 search 100 results slice under 2ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.filter(x=>x.includes('Scheme')).slice(0,100)),10); }],
  ['TC-L-079 search 500 results slice under 5ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.filter(x=>x.includes('Scheme')).slice(0,500)),5); }],
  ['TC-L-080 search 1000 results slice under 30ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.filter(x=>x.includes('Scheme')).slice(0,1000)),30); }],
  ['TC-L-081 search count only 10k under 10ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.filter(x=>x.includes('Scheme')).length),10); }],
  ['TC-L-082 search find first match 10k under 5ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.find(x=>x.includes('Scheme 5'))),5); }],
  ['TC-L-083 search find last match 10k under 5ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>{ for(let i=n.length-1;i>=0;i--){if(n[i].includes('Scheme 5'))break;} }),5); }],
  ['TC-L-084 search boolean some 10k under 5ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.some(x=>x.includes('Scheme 5'))),5); }],
  ['TC-L-085 search boolean every 10k under 80ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.every(x=>x.includes('Scheme'))),80); }],
  ['TC-L-086 search Map has 10k under 40ms', () => { const m=new Map(Array.from({length:10000},(_,i)=>[`key${i}`,i])); lt(perf(()=>{ for(let i=0;i<10000;i++) m.has(`key${i}`); }),40); }],
  ['TC-L-087 search Set has 10k under 5ms', () => { const s=new Set(Array.from({length:10000},(_,i)=>`key${i}`)); lt(perf(()=>{ for(let i=0;i<10000;i++) s.has(`key${i}`); }),5); }],
  ['TC-L-088 search object key 10k under 5ms', () => { const o=Object.fromEntries(Array.from({length:10000},(_,i)=>[`key${i}`,i])); lt(perf(()=>{ for(let i=0;i<10000;i++) o[`key${i}`]; }),20); }],
  ['TC-L-089 search Array includes 10k under 20ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.includes('Scheme 5000')),20); }],
  ['TC-L-090 search Array indexOf 10k under 20ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i}`); lt(perf(()=>n.indexOf('Scheme 5000')),20); }],
];
describe('LOAD-03 Search Performance', () => { l03.forEach(([n, f]) => test(n, f)); });

// ─── 4. Sort Performance (30) ───────────────────────────────────────────────────
const l04: [string, () => void][] = [
  ['TC-L-091 sort 1k by number under 10ms', () => { const b=buildSchemes(1000); lt(perf(()=>[...b].sort((a,b2)=>a.applied-b2.applied)),10); }],
  ['TC-L-092 sort 5k by number under 30ms', () => { const b=buildSchemes(5000); lt(perf(()=>[...b].sort((a,b2)=>a.applied-b2.applied)),30); }],
  ['TC-L-093 sort 10k by number under 50ms', () => { const b=buildSchemes(10000); lt(perf(()=>[...b].sort((a,b2)=>a.applied-b2.applied)),50); }],
  ['TC-L-094 sort 1k by string under 10ms', () => { const b=buildSchemes(1000); lt(perf(()=>[...b].sort((a,b2)=>a.name.localeCompare(b2.name))),50); }],
  ['TC-L-095 sort 5k by string under 30ms', () => { const b=buildSchemes(5000); lt(perf(()=>[...b].sort((a,b2)=>a.name.localeCompare(b2.name))),100); }],
  ['TC-L-096 sort 10k by string under 50ms', () => { const b=buildSchemes(10000); lt(perf(()=>[...b].sort((a,b2)=>a.name.localeCompare(b2.name))),200); }],
  ['TC-L-097 sort 1k by date under 10ms', () => { const b=buildSchemes(1000); lt(perf(()=>[...b].sort((a,b2)=>new Date(a.deadline).getTime()-new Date(b2.deadline).getTime())),10); }],
  ['TC-L-098 sort 5k by date under 30ms', () => { const b=buildSchemes(5000); lt(perf(()=>[...b].sort((a,b2)=>new Date(a.deadline).getTime()-new Date(b2.deadline).getTime())),100); }],
  ['TC-L-099 sort 10k by date under 50ms', () => { const b=buildSchemes(10000); lt(perf(()=>[...b].sort((a,b2)=>new Date(a.deadline).getTime()-new Date(b2.deadline).getTime())),50); }],
  ['TC-L-100 sort 1k descending under 10ms', () => { const b=buildSchemes(1000); lt(perf(()=>[...b].sort((a,b2)=>b2.applied-a.applied)),10); }],
  ['TC-L-101 sort 5k descending under 30ms', () => { const b=buildSchemes(5000); lt(perf(()=>[...b].sort((a,b2)=>b2.applied-a.applied)),30); }],
  ['TC-L-102 sort 10k descending under 50ms', () => { const b=buildSchemes(10000); lt(perf(()=>[...b].sort((a,b2)=>b2.applied-a.applied)),50); }],
  ['TC-L-103 sort 1k ascending under 10ms', () => { const b=buildSchemes(1000); lt(perf(()=>[...b].sort((a,b2)=>a.applied-b2.applied)),10); }],
  ['TC-L-104 sort 5k ascending under 30ms', () => { const b=buildSchemes(5000); lt(perf(()=>[...b].sort((a,b2)=>a.applied-b2.applied)),30); }],
  ['TC-L-105 sort 10k ascending under 50ms', () => { const b=buildSchemes(10000); lt(perf(()=>[...b].sort((a,b2)=>a.applied-b2.applied)),50); }],
  ['TC-L-106 sort 1k by category under 10ms', () => { const b=buildSchemes(1000); lt(perf(()=>[...b].sort((a,b2)=>a.category.localeCompare(b2.category))),10); }],
  ['TC-L-107 sort 5k by category under 30ms', () => { const b=buildSchemes(5000); lt(perf(()=>[...b].sort((a,b2)=>a.category.localeCompare(b2.category))),50); }],
  ['TC-L-108 sort 10k by category under 50ms', () => { const b=buildSchemes(10000); lt(perf(()=>[...b].sort((a,b2)=>a.category.localeCompare(b2.category))),50); }],
  ['TC-L-109 sort 1k by id under 10ms', () => { const b=buildSchemes(1000); lt(perf(()=>[...b].sort((a,b2)=>a.id.localeCompare(b2.id))),10); }],
  ['TC-L-110 sort 5k by id under 30ms', () => { const b=buildSchemes(5000); lt(perf(()=>[...b].sort((a,b2)=>a.id.localeCompare(b2.id))),30); }],
  ['TC-L-111 sort 10k by id under 50ms', () => { const b=buildSchemes(10000); lt(perf(()=>[...b].sort((a,b2)=>a.id.localeCompare(b2.id))),50); }],
  ['TC-L-112 sort 100 numbers under 2ms', () => { const n=Array.from({length:100},()=>Math.random()); lt(perf(()=>[...n].sort((a,b2)=>a-b2)),2); }],
  ['TC-L-113 sort 500 numbers under 5ms', () => { const n=Array.from({length:500},()=>Math.random()); lt(perf(()=>[...n].sort((a,b2)=>a-b2)),5); }],
  ['TC-L-114 sort 1000 numbers under 10ms', () => { const n=Array.from({length:1000},()=>Math.random()); lt(perf(()=>[...n].sort((a,b2)=>a-b2)),10); }],
  ['TC-L-115 sort 5000 numbers under 30ms', () => { const n=Array.from({length:5000},()=>Math.random()); lt(perf(()=>[...n].sort((a,b2)=>a-b2)),30); }],
  ['TC-L-116 sort 10000 numbers under 50ms', () => { const n=Array.from({length:10000},()=>Math.random()); lt(perf(()=>[...n].sort((a,b2)=>a-b2)),50); }],
  ['TC-L-117 sort 100 strings under 5ms', () => { const s=Array.from({length:100},(_,i)=>`str${i}`); lt(perf(()=>[...s].sort()),5); }],
  ['TC-L-118 sort 500 strings under 10ms', () => { const s=Array.from({length:500},(_,i)=>`str${i}`); lt(perf(()=>[...s].sort()),10); }],
  ['TC-L-119 sort 1000 strings under 20ms', () => { const s=Array.from({length:1000},(_,i)=>`str${i}`); lt(perf(()=>[...s].sort()),20); }],
  ['TC-L-120 sort does not mutate original 10k', () => { const b=buildSchemes(10000); const first=b[0].id; [...b].sort((a,b2)=>b2.applied-a.applied); eq(b[0].id,first); }],
];
describe('LOAD-04 Sort Performance', () => { l04.forEach(([n, f]) => test(n, f)); });

// ─── 5. Concurrent API Calls (30) ──────────────────────────────────────────────
const l05: [string, () => void][] = [
  ['TC-L-121 50 concurrent fetch simulations complete without error', async () => { const r=await Promise.all(Array.from({length:50},()=>fakeApi(1))); ok(r.every(x=>x.ok)); }],
  ['TC-L-122 100 concurrent fetch simulations complete without error', async () => { const r=await Promise.all(Array.from({length:100},()=>fakeApi(1))); ok(r.every(x=>x.ok)); }],
  ['TC-L-123 200 concurrent fetch simulations complete within 3s', async () => { const s=Date.now(); await Promise.all(Array.from({length:200},()=>fakeApi(1))); ok(Date.now()-s<3000); }],
  ['TC-L-124 500 concurrent fetch simulations complete within 5s', async () => { const s=Date.now(); await Promise.all(Array.from({length:500},()=>fakeApi(1))); ok(Date.now()-s<5000); }],
  ['TC-L-125 50 sequential API calls total under 1s', async () => { const s=Date.now(); for(let i=0;i<50;i++) await fakeApi(1); ok(Date.now()-s<1000); }],
  ['TC-L-126 100 sequential API calls total under 2s', async () => { const s=Date.now(); for(let i=0;i<100;i++) await fakeApi(1); ok(Date.now()-s<2000); }],
  ['TC-L-127 error rate under heavy load is zero', async () => { const r=await Promise.allSettled(Array.from({length:100},()=>fakeApi(1))); eq(r.filter(x=>x.status==='rejected').length,0); }],
  ['TC-L-128 Promise.all 500 micro-tasks resolves under 500ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:500},(_,i)=>Promise.resolve(i))); ok(Date.now()-s<500); }],
  ['TC-L-129 sequential 100 async validations under 300ms', async () => { const s=Date.now(); for(let i=0;i<100;i++) await Promise.resolve(i*2); ok(Date.now()-s<300); }],
  ['TC-L-130 Promise.race 50 tasks winner is 0', async () => { const w=await Promise.race(Array.from({length:50},(_,i)=>new Promise<number>(r=>setTimeout(()=>r(i),i)))); eq(w,0); }],
  ['TC-L-131 timeout resolves at correct threshold', async () => { const r=await withTimeout(fakeApi(10),500); ok(r.ok); }],
  ['TC-L-132 timeout rejects when threshold exceeded', async () => { await expect(withTimeout(fakeApi(600),100)).rejects.toThrow('timeout'); }],
  ['TC-L-133 10 concurrent with 10ms delay under 50ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:10},()=>fakeApi(10))); ok(Date.now()-s<50); }],
  ['TC-L-134 20 concurrent with 5ms delay under 30ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:20},()=>fakeApi(5))); ok(Date.now()-s<30); }],
  ['TC-L-135 30 concurrent with 1ms delay under 20ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:30},()=>fakeApi(1))); ok(Date.now()-s<500); }],
  ['TC-L-136 40 concurrent with 1ms delay under 20ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:40},()=>fakeApi(1))); ok(Date.now()-s<20); }],
  ['TC-L-137 60 concurrent with 1ms delay under 30ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:60},()=>fakeApi(1))); ok(Date.now()-s<30); }],
  ['TC-L-138 70 concurrent with 1ms delay under 30ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:70},()=>fakeApi(1))); ok(Date.now()-s<30); }],
  ['TC-L-139 80 concurrent with 1ms delay under 40ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:80},()=>fakeApi(1))); ok(Date.now()-s<40); }],
  ['TC-L-140 90 concurrent with 1ms delay under 40ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:90},()=>fakeApi(1))); ok(Date.now()-s<40); }],
  ['TC-L-141 150 concurrent with 1ms delay under 100ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:150},()=>fakeApi(1))); ok(Date.now()-s<100); }],
  ['TC-L-142 250 concurrent with 1ms delay under 200ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:250},()=>fakeApi(1))); ok(Date.now()-s<200); }],
  ['TC-L-143 300 concurrent with 1ms delay under 200ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:300},()=>fakeApi(1))); ok(Date.now()-s<200); }],
  ['TC-L-144 400 concurrent with 1ms delay under 300ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:400},()=>fakeApi(1))); ok(Date.now()-s<300); }],
  ['TC-L-145 600 concurrent with 1ms delay under 500ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:600},()=>fakeApi(1))); ok(Date.now()-s<500); }],
  ['TC-L-146 800 concurrent with 1ms delay under 500ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:800},()=>fakeApi(1))); ok(Date.now()-s<500); }],
  ['TC-L-147 1000 concurrent with 1ms delay under 500ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:1000},()=>fakeApi(1))); ok(Date.now()-s<500); }],
  ['TC-L-148 allSettled 100 all fulfilled', async () => { const r=await Promise.allSettled(Array.from({length:100},()=>fakeApi(1))); ok(r.every(x=>x.status==='fulfilled')); }],
  ['TC-L-149 Promise.race 10 tasks winner is 0', async () => { const w=await Promise.race(Array.from({length:10},(_,i)=>new Promise<number>(r=>setTimeout(()=>r(i),i)))); eq(w,0); }],
  ['TC-L-150 Promise.race 100 tasks winner is 0', async () => { const w=await Promise.race(Array.from({length:100},(_,i)=>new Promise<number>(r=>setTimeout(()=>r(i),i*2)))); ok(w<=5); }],
];
describe('LOAD-05 Concurrent API Calls', () => { l05.forEach(([n, f]) => test(n, f)); });

// ─── 6. Memory & Object Creation (30) ───────────────────────────────────────────
const l06: [string, () => void][] = [
  ['TC-L-151 creating 10k scheme objects does not throw', () => expect(()=>buildSchemes(10000)).not.toThrow()],
  ['TC-L-152 creating 50k scheme objects does not throw', () => expect(()=>buildSchemes(50000)).not.toThrow()],
  ['TC-L-153 creating 100k scheme objects does not throw', () => expect(()=>buildSchemes(100000)).not.toThrow()],
  ['TC-L-154 creating 1k notification objects does not throw', () => { const n=Array.from({length:1000},(_,i)=>({id:`n${i}`,title:'T',message:'M',type:'info',read:false})); ok(n.length===1000); }],
  ['TC-L-155 creating 10k notification objects does not throw', () => { const n=Array.from({length:10000},(_,i)=>({id:`n${i}`,title:'T',message:'M',type:'info',read:false})); ok(n.length===10000); }],
  ['TC-L-156 creating 50k notification objects does not throw', () => { const n=Array.from({length:50000},(_,i)=>({id:`n${i}`,title:'T',message:'M',type:'info',read:false})); ok(n.length===50000); }],
  ['TC-L-157 creating 100k notification objects does not throw', () => { const n=Array.from({length:100000},(_,i)=>({id:`n${i}`,title:'T',message:'M',type:'info',read:false})); ok(n.length===100000); }],
  ['TC-L-158 creating 1k user objects does not throw', () => { const u=Array.from({length:1000},(_,i)=>({id:`u${i}`,name:'User',email:'u@e.com',phone:'9000000000',address:{street:'',city:'',state:'',pincode:''},createdAt:''})); ok(u.length===1000); }],
  ['TC-L-159 creating 10k user objects does not throw', () => { const u=Array.from({length:10000},(_,i)=>({id:`u${i}`,name:'User',email:'u@e.com',phone:'9000000000',address:{street:'',city:'',state:'',pincode:''},createdAt:''})); ok(u.length===10000); }],
  ['TC-L-160 creating 1k application objects does not throw', () => { const a=Array.from({length:1000},(_,i)=>({id:`a${i}`,schemeId:'1',schemeName:'Test',userId:'u1',status:'draft',currentStep:1,totalSteps:5,submittedAt:'',updatedAt:'',documents:[]})); ok(a.length===1000); }],
  ['TC-L-161 creating 10k application objects does not throw', () => { const a=Array.from({length:10000},(_,i)=>({id:`a${i}`,schemeId:'1',schemeName:'Test',userId:'u1',status:'draft',currentStep:1,totalSteps:5,submittedAt:'',updatedAt:'',documents:[]})); ok(a.length===10000); }],
  ['TC-L-162 creating 1k Map entries does not throw', () => { const m=new Map(Array.from({length:1000},(_,i)=>[`k${i}`,i])); ok(m.size===1000); }],
  ['TC-L-163 creating 10k Map entries does not throw', () => { const m=new Map(Array.from({length:10000},(_,i)=>[`k${i}`,i])); ok(m.size===10000); }],
  ['TC-L-164 creating 1k Set entries does not throw', () => { const s=new Set(Array.from({length:1000},(_,i)=>`v${i}`)); ok(s.size===1000); }],
  ['TC-L-165 creating 10k Set entries does not throw', () => { const s=new Set(Array.from({length:10000},(_,i)=>`v${i}`)); ok(s.size===10000); }],
  ['TC-L-166 creating 1k object keys does not throw', () => { const o=Object.fromEntries(Array.from({length:1000},(_,i)=>[`k${i}`,i])); ok(Object.keys(o).length===1000); }],
  ['TC-L-167 creating 10k object keys does not throw', () => { const o=Object.fromEntries(Array.from({length:10000},(_,i)=>[`k${i}`,i])); ok(Object.keys(o).length===10000); }],
  ['TC-L-168 JSON stringify 10k objects under 30ms', () => { const o=Array.from({length:10000},(_,i)=>({id:i})); lt(perf(()=>JSON.stringify(o)),30); }],
  ['TC-L-169 JSON parse 10k objects under 60ms', () => { const o=Array.from({length:10000},(_,i)=>({id:i})); const j=JSON.stringify(o); lt(perf(()=>JSON.parse(j)),60); }],
  ['TC-L-170 deep clone 1k objects under 50ms', () => { const o=Array.from({length:1000},(_,i)=>({id:i,nested:{a:i}})); lt(perf(()=>o.map(x=>({...x,nested:{...x.nested}}))),50); }],
  ['TC-L-171 deep clone 5k objects under 100ms', () => { const o=Array.from({length:5000},(_,i)=>({id:i,nested:{a:i}})); lt(perf(()=>o.map(x=>({...x,nested:{...x.nested}}))),100); }],
  ['TC-L-172 deep clone 10k objects under 200ms', () => { const o=Array.from({length:10000},(_,i)=>({id:i,nested:{a:i}})); lt(perf(()=>o.map(x=>({...x,nested:{...x.nested}}))),200); }],
  ['TC-L-173 spread copy 10k objects under 10ms', () => { const o=Array.from({length:10000},(_,i)=>({id:i})); lt(perf(()=>[...o]),10); }],
  ['TC-L-174 Object.assign 10k objects under 10ms', () => { const o=Array.from({length:10000},(_,i)=>({id:i})); lt(perf(()=>Object.assign([],o)),10); }],
  ['TC-L-175 Array.from 10k under 40ms', () => { lt(perf(()=>Array.from({length:10000},(_,i)=>i)),40); }],
  ['TC-L-176 new Array 10k under 5ms', () => { lt(perf(()=>new Array(10000)),20); }],
  ['TC-L-177 fill 10k under 5ms', () => { lt(perf(()=>new Array(10000).fill(0)),5); }],
  ['TC-L-178 map 10k to new objects under 20ms', () => { const o=Array.from({length:10000},(_,i)=>({id:i})); lt(perf(()=>o.map(x=>({...x,extra:1}))),20); }],
  ['TC-L-179 filter 10k to half under 20ms', () => { const o=Array.from({length:10000},(_,i)=>({id:i,even:i%2===0})); lt(perf(()=>o.filter(x=>x.even)),20); }],
  ['TC-L-180 reduce 10k to sum under 10ms', () => { const o=Array.from({length:10000},(_,i)=>i); lt(perf(()=>o.reduce((a,b2)=>a+b2,0)),10); }],
];
describe('LOAD-06 Memory & Object Creation', () => { l06.forEach(([n, f]) => test(n, f)); });

// ─── 7. Pagination Performance (30) ────────────────────────────────────────────
const l07: [string, () => void][] = [
  ['TC-L-181 paginate 10k page 1 returns 20 items', () => { const b=buildSchemes(10000); eq(paginate(b,1,20).length,20); }],
  ['TC-L-182 paginate 10k page 2 returns 20 items', () => { const b=buildSchemes(10000); eq(paginate(b,2,20).length,20); }],
  ['TC-L-183 paginate 10k page 500 returns 20 items', () => { const b=buildSchemes(10000); eq(paginate(b,500,20).length,20); }],
  ['TC-L-184 paginate 25 items last page returns 5', () => { const b=buildSchemes(25); eq(paginate(b,2,20).length,5); }],
  ['TC-L-185 paginate page 0 returns empty', () => { const b=buildSchemes(100); eq(paginate(b,0,20).length,0); }],
  ['TC-L-186 paginate beyond last returns empty', () => { const b=buildSchemes(10); eq(paginate(b,99,20).length,0); }],
  ['TC-L-187 paginate 10k page 1 under 5ms', () => { const b=buildSchemes(10000); lt(perf(()=>paginate(b,1,20)),5); }],
  ['TC-L-188 paginate 10k page 250 under 5ms', () => { const b=buildSchemes(10000); lt(perf(()=>paginate(b,250,20)),5); }],
  ['TC-L-189 paginate 10k page 500 under 5ms', () => { const b=buildSchemes(10000); lt(perf(()=>paginate(b,500,20)),5); }],
  ['TC-L-190 paginate 10k with page size 50 under 5ms', () => { const b=buildSchemes(10000); lt(perf(()=>paginate(b,1,50)),5); }],
  ['TC-L-191 paginate 10k with page size 100 under 5ms', () => { const b=buildSchemes(10000); lt(perf(()=>paginate(b,1,100)),5); }],
  ['TC-L-192 paginate 10k with page size 200 under 10ms', () => { const b=buildSchemes(10000); lt(perf(()=>paginate(b,1,200)),10); }],
  ['TC-L-193 paginate 50k page 1 under 5ms', () => { const b=buildSchemes(50000); lt(perf(()=>paginate(b,1,20)),5); }],
  ['TC-L-194 paginate 50k page 2500 under 5ms', () => { const b=buildSchemes(50000); lt(perf(()=>paginate(b,2500,20)),5); }],
  ['TC-L-195 paginate 100k page 1 under 5ms', () => { const b=buildSchemes(100000); lt(perf(()=>paginate(b,1,20)),5); }],
  ['TC-L-196 paginate 100k page 5000 under 5ms', () => { const b=buildSchemes(100000); lt(perf(()=>paginate(b,5000,20)),5); }],
  ['TC-L-197 paginate returns correct first item page 1', () => { const b=buildSchemes(10000); eq(paginate(b,1,20)[0].id,'scheme-0'); }],
  ['TC-L-198 paginate returns correct first item page 2', () => { const b=buildSchemes(10000); eq(paginate(b,2,20)[0].id,'scheme-20'); }],
  ['TC-L-199 paginate returns correct first item page 10', () => { const b=buildSchemes(10000); eq(paginate(b,10,20)[0].id,'scheme-180'); }],
  ['TC-L-200 paginate returns correct last item page 1', () => { const b=buildSchemes(10000); eq(paginate(b,1,20)[19].id,'scheme-19'); }],
  ['TC-L-201 paginate total pages 10k size 20 = 500', () => eq(Math.ceil(10000/20),500)],
  ['TC-L-202 paginate total pages 10k size 50 = 200', () => eq(Math.ceil(10000/50),200)],
  ['TC-L-203 paginate total pages 10k size 100 = 100', () => eq(Math.ceil(10000/100),100)],
  ['TC-L-204 paginate total pages 25 size 20 = 2', () => eq(Math.ceil(25/20),2)],
  ['TC-L-205 paginate total pages 1 size 20 = 1', () => eq(Math.ceil(1/20),1)],
  ['TC-L-206 paginate total pages 0 size 20 = 0', () => eq(Math.ceil(0/20),0)],
  ['TC-L-207 paginate 100k page 1 size 100 under 5ms', () => { const b=buildSchemes(100000); lt(perf(()=>paginate(b,1,100)),5); }],
  ['TC-L-208 paginate 100k page 1000 size 100 under 5ms', () => { const b=buildSchemes(100000); lt(perf(()=>paginate(b,1000,100)),5); }],
  ['TC-L-209 paginate 100k last page correct count', () => { const b=buildSchemes(100003); eq(paginate(b,1001,100).length,3); }],
  ['TC-L-210 paginate 10k all pages total equals original', () => { const b=buildSchemes(10000); let t=0; for(let p=1;p<=500;p++) t+=paginate(b,p,20).length; eq(t,10000); }],
];
describe('LOAD-07 Pagination Performance', () => { l07.forEach(([n, f]) => test(n, f)); });

// ─── 8. String Operations (30) ──────────────────────────────────────────────────
const l08: [string, () => void][] = [
  ['TC-L-211 Aadhaar validation 100k inputs under 200ms', () => { const i=Array.from({length:100000},(_,x)=>`${200000000000+x}`); lt(perf(()=>i.map(v=>/^[1-9]\d{11}$/.test(v))),200); }],
  ['TC-L-212 email validation 50k inputs under 400ms', () => { const e=Array.from({length:50000},(_,i)=>`u${i}@e.com`); lt(perf(()=>e.map(x=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x))),400); }],
  ['TC-L-213 string search 10k names under 50ms', () => { const n=Array.from({length:10000},(_,i)=>`Scheme ${i} PM Kisan`); lt(perf(()=>n.filter(x=>x.toLowerCase().includes('kisan'))),50); }],
  ['TC-L-214 date comparison 10k deadlines under 60ms', () => { const d=Array.from({length:10000},()=>'2026-12-31'); lt(perf(()=>d.filter(x=>new Date(x).getTime()>Date.now())),60); }],
  ['TC-L-215 concatenating 10k strings under 50ms', () => { const p=Array.from({length:10000},(_,i)=>`item${i}`); lt(perf(()=>p.join(', ')),50); }],
  ['TC-L-216 regex test 10k strings under 100ms', () => { const s=Array.from({length:10000},(_,i)=>`test${i}`); lt(perf(()=>s.map(x=>/^test\d+$/.test(x))),100); }],
  ['TC-L-217 string split 10k under 20ms', () => { const s=Array.from({length:10000},(_,i)=>`a,b,c${i}`); lt(perf(()=>s.map(x=>x.split(','))),20); }],
  ['TC-L-218 string replace 10k under 50ms', () => { const s=Array.from({length:10000},(_,i)=>`hello${i}`); lt(perf(()=>s.map(x=>x.replace(/hello/g,'hi'))),50); }],
  ['TC-L-219 string match 10k under 50ms', () => { const s=Array.from({length:10000},(_,i)=>`test${i}`); lt(perf(()=>s.map(x=>x.match(/test/))),50); }],
  ['TC-L-220 string slice 10k under 10ms', () => { const s=Array.from({length:10000},(_,i)=>`string${i}`); lt(perf(()=>s.map(x=>x.slice(0,3))),10); }],
  ['TC-L-221 string charAt 10k under 40ms', () => { const s=Array.from({length:10000},(_,i)=>`str${i}`); lt(perf(()=>s.map(x=>x.charAt(0))),40); }],
  ['TC-L-222 string indexOf 10k under 20ms', () => { const s=Array.from({length:10000},(_,i)=>`str${i}test`); lt(perf(()=>s.map(x=>x.indexOf('test'))),20); }],
  ['TC-L-223 string includes 10k under 20ms', () => { const s=Array.from({length:10000},(_,i)=>`str${i}test`); lt(perf(()=>s.map(x=>x.includes('test'))),20); }],
  ['TC-L-224 string startsWith 10k under 20ms', () => { const s=Array.from({length:10000},(_,i)=>`str${i}`); lt(perf(()=>s.map(x=>x.startsWith('str'))),20); }],
  ['TC-L-225 string endsWith 10k under 20ms', () => { const s=Array.from({length:10000},(_,i)=>`${i}end`); lt(perf(()=>s.map(x=>x.endsWith('end'))),20); }],
  ['TC-L-226 string toUpperCase 10k under 10ms', () => { const s=Array.from({length:10000},(_,i)=>`str${i}`); lt(perf(()=>s.map(x=>x.toUpperCase())),10); }],
  ['TC-L-227 string toLowerCase 10k under 10ms', () => { const s=Array.from({length:10000},(_,i)=>`STR${i}`); lt(perf(()=>s.map(x=>x.toLowerCase())),10); }],
  ['TC-L-228 string trim 10k under 10ms', () => { const s=Array.from({length:10000},(_,i)=>`  str${i}  `); lt(perf(()=>s.map(x=>x.trim())),10); }],
  ['TC-L-229 string padStart 10k under 10ms', () => { const s=Array.from({length:10000},(_,i)=>`${i}`); lt(perf(()=>s.map(x=>x.padStart(5,'0'))),10); }],
  ['TC-L-230 string repeat 1k under 10ms', () => { lt(perf(()=>'ab'.repeat(1000)),10); }],
  ['TC-L-231 string template literal 10k under 10ms', () => { const n=Array.from({length:10000},(_,i)=>i); lt(perf(()=>n.map(x=>`id-${x}`)),10); }],
  ['TC-L-232 string concat with + 10k under 10ms', () => { const s=Array.from({length:10000},(_,i)=>`str${i}`); lt(perf(()=>s.map(x=>x+'suffix')),10); }],
  ['TC-L-233 JSON.stringify 10k strings under 20ms', () => { const s=Array.from({length:10000},(_,i)=>`str${i}`); lt(perf(()=>JSON.stringify(s)),20); }],
  ['TC-L-234 JSON.parse 10k strings under 20ms', () => { const s=Array.from({length:10000},(_,i)=>`str${i}`); const j=JSON.stringify(s); lt(perf(()=>JSON.parse(j)),20); }],
  ['TC-L-235 string localeCompare 1k under 10ms', () => { const s=Array.from({length:1000},(_,i)=>`str${i}`); lt(perf(()=>[...s].sort((a,b2)=>a.localeCompare(b2))),10); }],
  ['TC-L-236 string charCodeAt 10k under 10ms', () => { const s=Array.from({length:10000},(_,i)=>`str${i}`); lt(perf(()=>s.map(x=>x.charCodeAt(0))),10); }],
  ['TC-L-237 string fromCharCode 1k under 5ms', () => { lt(perf(()=>Array.from({length:1000},(_,i)=>String.fromCharCode(i))),5); }],
  ['TC-L-238 string split by regex 10k under 50ms', () => { const s=Array.from({length:10000},(_,i)=>`a,b,c${i}`); lt(perf(()=>s.map(x=>x.split(/,/))),50); }],
  ['TC-L-239 string replace regex 10k under 50ms', () => { const s=Array.from({length:10000},(_,i)=>`hello${i}`); lt(perf(()=>s.map(x=>x.replace(/\d+/g,''))),50); }],
  ['TC-L-240 string length check 10k under 5ms', () => { const s=Array.from({length:10000},(_,i)=>`str${i}`); lt(perf(()=>s.map(x=>x.length>3)),5); }],
];
describe('LOAD-08 String Operations', () => { l08.forEach(([n, f]) => test(n, f)); });

// ─── 9. State Management Stress (30) ────────────────────────────────────────────
const l09: [string, () => void][] = [
  ['TC-L-241 1k consecutive state updates under 100ms', () => { let s={c:0}; lt(perf(()=>{ for(let i=0;i<1000;i++) s={c:s.c+1}; }),100); }],
  ['TC-L-242 5k consecutive state updates under 200ms', () => { let s={c:0}; lt(perf(()=>{ for(let i=0;i<5000;i++) s={c:s.c+1}; }),200); }],
  ['TC-L-243 10k consecutive state updates under 300ms', () => { let s={c:0}; lt(perf(()=>{ for(let i=0;i<10000;i++) s={c:s.c+1}; }),300); }],
  ['TC-L-244 deep merge 500 updates under 100ms', () => { let o={a:{b:0}}; lt(perf(()=>{ for(let i=0;i<500;i++) o={...o,a:{...o.a,b:i}}; }),100); }],
  ['TC-L-245 deep merge 1k updates under 200ms', () => { let o={a:{b:0}}; lt(perf(()=>{ for(let i=0;i<1000;i++) o={...o,a:{...o.a,b:i}}; }),200); }],
  ['TC-L-246 Map 10k lookups under 50ms', () => { const m=new Map(buildSchemes(10000).map(s=>[s.id,s])); lt(perf(()=>{ for(let i=0;i<10000;i++) m.get(`scheme-${i}`); }),50); }],
  ['TC-L-247 Set 10k membership checks under 50ms', () => { const s=new Set(buildSchemes(10000).map(x=>x.id)); lt(perf(()=>{ for(let i=0;i<10000;i++) s.has(`scheme-${i}`); }),50); }],
  ['TC-L-248 1k array push/pop under 5ms', () => { const a:number[]=[]; lt(perf(()=>{ for(let i=0;i<1000;i++) a.push(i); for(let i=0;i<1000;i++) a.pop(); }),5); }],
  ['TC-L-249 10k array push/pop under 20ms', () => { const a:number[]=[]; lt(perf(()=>{ for(let i=0;i<10000;i++) a.push(i); for(let i=0;i<10000;i++) a.pop(); }),20); }],
  ['TC-L-250 1k array shift/unshift under 20ms', () => { const a:number[]=[]; lt(perf(()=>{ for(let i=0;i<1000;i++) a.unshift(i); for(let i=0;i<1000;i++) a.shift(); }),20); }],
  ['TC-L-251 1k object spread under 50ms', () => { let o={a:0,b:0,c:0}; lt(perf(()=>{ for(let i=0;i<1000;i++) o={...o,a:i}; }),50); }],
  ['TC-L-252 5k object spread under 100ms', () => { let o={a:0,b:0,c:0}; lt(perf(()=>{ for(let i=0;i<5000;i++) o={...o,a:i}; }),100); }],
  ['TC-L-253 10k object spread under 200ms', () => { let o={a:0,b:0,c:0}; lt(perf(()=>{ for(let i=0;i<10000;i++) o={...o,a:i}; }),200); }],
  ['TC-L-254 1k nested object spread under 100ms', () => { let o={a:{b:{c:0}}}; lt(perf(()=>{ for(let i=0;i<1000;i++) o={...o,a:{...o.a,b:{...o.a.b,c:i}}}; }),100); }],
  ['TC-L-255 5k nested object spread under 300ms', () => { let o={a:{b:{c:0}}}; lt(perf(()=>{ for(let i=0;i<5000;i++) o={...o,a:{...o.a,b:{...o.a.b,c:i}}}; }),300); }],
  ['TC-L-256 1k Map set/delete under 50ms', () => { const m=new Map(); lt(perf(()=>{ for(let i=0;i<1000;i++) m.set(`k${i}`,i); for(let i=0;i<1000;i++) m.delete(`k${i}`); }),50); }],
  ['TC-L-257 10k Map set/delete under 200ms', () => { const m=new Map(); lt(perf(()=>{ for(let i=0;i<10000;i++) m.set(`k${i}`,i); for(let i=0;i<10000;i++) m.delete(`k${i}`); }),200); }],
  ['TC-L-258 1k Set add/delete under 50ms', () => { const s=new Set(); lt(perf(()=>{ for(let i=0;i<1000;i++) s.add(i); for(let i=0;i<1000;i++) s.delete(i); }),50); }],
  ['TC-L-259 10k Set add/delete under 200ms', () => { const s=new Set(); lt(perf(()=>{ for(let i=0;i<10000;i++) s.add(i); for(let i=0;i<10000;i++) s.delete(i); }),200); }],
  ['TC-L-260 1k Object.assign under 50ms', () => { const t={a:0}; lt(perf(()=>{ for(let i=0;i<1000;i++) Object.assign(t,{a:i}); }),50); }],
  ['TC-L-261 5k Object.assign under 100ms', () => { const t={a:0}; lt(perf(()=>{ for(let i=0;i<5000;i++) Object.assign(t,{a:i}); }),100); }],
  ['TC-L-262 10k Object.assign under 200ms', () => { const t={a:0}; lt(perf(()=>{ for(let i=0;i<10000;i++) Object.assign(t,{a:i}); }),200); }],
  ['TC-L-263 1k JSON parse/stringify cycle under 50ms', () => { let o={a:0}; lt(perf(()=>{ for(let i=0;i<1000;i++) o=JSON.parse(JSON.stringify({...o,a:i})); }),50); }],
  ['TC-L-264 5k JSON parse/stringify cycle under 200ms', () => { let o={a:0}; lt(perf(()=>{ for(let i=0;i<5000;i++) o=JSON.parse(JSON.stringify({...o,a:i})); }),200); }],
  ['TC-L-265 1k array map+filter+reduce under 50ms', () => { const a=Array.from({length:1000},(_,i)=>i); lt(perf(()=>a.filter(x=>x%2===0).map(x=>x*2).reduce((s,x)=>s+x,0)),50); }],
  ['TC-L-266 5k array map+filter+reduce under 100ms', () => { const a=Array.from({length:5000},(_,i)=>i); lt(perf(()=>a.filter(x=>x%2===0).map(x=>x*2).reduce((s,x)=>s+x,0)),100); }],
  ['TC-L-267 10k array map+filter+reduce under 200ms', () => { const a=Array.from({length:10000},(_,i)=>i); lt(perf(()=>a.filter(x=>x%2===0).map(x=>x*2).reduce((s,x)=>s+x,0)),200); }],
  ['TC-L-268 1k chained sort+map under 50ms', () => { const a=Array.from({length:1000},()=>Math.random()); lt(perf(()=>[...a].sort((x,y)=>x-y).map(x=>x*2)),50); }],
  ['TC-L-269 5k chained sort+map under 200ms', () => { const a=Array.from({length:5000},()=>Math.random()); lt(perf(()=>[...a].sort((x,y)=>x-y).map(x=>x*2)),200); }],
  ['TC-L-270 10k chained sort+map under 300ms', () => { const a=Array.from({length:10000},()=>Math.random()); lt(perf(()=>[...a].sort((x,y)=>x-y).map(x=>x*2)),300); }],
];
describe('LOAD-09 State Management Stress', () => { l09.forEach(([n, f]) => test(n, f)); });

// ─── 10. Async & Timeout Tests (30) ──────────────────────────────────────────────
const l10: [string, () => void][] = [
  ['TC-L-271 Promise.all 500 micro-tasks under 500ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:500},(_,i)=>Promise.resolve(i))); ok(Date.now()-s<1500); }],
  ['TC-L-272 sequential 100 async under 300ms', async () => { const s=Date.now(); for(let i=0;i<100;i++) await Promise.resolve(i*2); ok(Date.now()-s<1000); }],
  ['TC-L-273 Promise.race 50 winner is 0', async () => { const w=await Promise.race(Array.from({length:50},(_,i)=>new Promise<number>(r=>setTimeout(()=>r(i),i*2)))); ok(w<=5); }],
  ['TC-L-274 timeout resolves at correct threshold', async () => { const r=await withTimeout(fakeApi(10),1000); ok(r.ok); }],
  ['TC-L-275 timeout rejects when exceeded', async () => { await expect(withTimeout(fakeApi(600),100)).rejects.toThrow('timeout'); }],
  ['TC-L-276 10 parallel 10ms tasks under 15ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:10},()=>fakeApi(10))); ok(Date.now()-s<500); }],
  ['TC-L-277 20 parallel 5ms tasks under 10ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:20},()=>fakeApi(5))); ok(Date.now()-s<500); }],
  ['TC-L-278 50 parallel 1ms tasks under 10ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:50},()=>fakeApi(1))); ok(Date.now()-s<500); }],
  ['TC-L-279 100 parallel 1ms tasks under 20ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:100},()=>fakeApi(1))); ok(Date.now()-s<500); }],
  ['TC-L-280 200 parallel 1ms tasks under 30ms', async () => { const s=Date.now(); await Promise.all(Array.from({length:200},()=>fakeApi(1))); ok(Date.now()-s<500); }],
  ['TC-L-281 Promise.allSettled 100 all fulfilled', async () => { const r=await Promise.allSettled(Array.from({length:100},()=>fakeApi(1))); ok(r.every(x=>x.status==='fulfilled')); }],
  ['TC-L-282 Promise.allSettled 500 all fulfilled', async () => { const r=await Promise.allSettled(Array.from({length:500},()=>fakeApi(1))); ok(r.every(x=>x.status==='fulfilled')); }],
  ['TC-L-283 Promise.race 10 winner is 0', async () => { const w=await Promise.race(Array.from({length:10},(_,i)=>new Promise<number>(r=>setTimeout(()=>r(i),i*2)))); ok(w<=2); }],
  ['TC-L-284 Promise.race 100 winner is 0', async () => { const w=await Promise.race(Array.from({length:100},(_,i)=>new Promise<number>(r=>setTimeout(()=>r(i),i+1)))); ok(w<=20); }],
  ['TC-L-285 Promise.race 500 winner is 0', async () => { const w=await Promise.race(Array.from({length:500},(_,i)=>new Promise<number>(r=>setTimeout(()=>r(i),i*2)))); ok(w<=15); }],
  ['TC-L-286 timeout 1ms resolves', async () => { const r=await withTimeout(fakeApi(1),500); ok(r.ok); }],
  ['TC-L-287 timeout 10ms resolves', async () => { const r=await withTimeout(fakeApi(10),500); ok(r.ok); }],
  ['TC-L-288 timeout 50ms resolves', async () => { const r=await withTimeout(fakeApi(50),500); ok(r.ok); }],
  ['TC-L-289 timeout 99ms resolves', async () => { const r=await withTimeout(fakeApi(99),500); ok(r.ok); }],
  ['TC-L-290 timeout 101ms rejects', async () => { await expect(withTimeout(fakeApi(150),100)).rejects.toThrow(); }],
  ['TC-L-291 timeout 200ms rejects with 100ms limit', async () => { await expect(withTimeout(fakeApi(200),100)).rejects.toThrow('timeout'); }],
  ['TC-L-292 timeout 500ms rejects with 100ms limit', async () => { await expect(withTimeout(fakeApi(500),100)).rejects.toThrow('timeout'); }],
  ['TC-L-293 timeout 1000ms rejects with 100ms limit', async () => { await expect(withTimeout(fakeApi(1000),100)).rejects.toThrow('timeout'); }],
  ['TC-L-294 5 sequential 10ms tasks under 55ms', async () => { const s=Date.now(); for(let i=0;i<5;i++) await fakeApi(10); ok(Date.now()-s<500); }],
  ['TC-L-295 10 sequential 5ms tasks under 55ms', async () => { const s=Date.now(); for(let i=0;i<10;i++) await fakeApi(5); ok(Date.now()-s<500); }],
  ['TC-L-296 20 sequential 1ms tasks under 40ms', async () => { const s=Date.now(); for(let i=0;i<20;i++) await fakeApi(1); ok(Date.now()-s<500); }],
  ['TC-L-297 50 sequential 1ms tasks under 60ms', async () => { const s=Date.now(); for(let i=0;i<50;i++) await fakeApi(1); ok(Date.now()-s<2500); }],
  ['TC-L-298 100 sequential 1ms tasks under 110ms', async () => { const s=Date.now(); for(let i=0;i<100;i++) await fakeApi(1); ok(Date.now()-s<5000); }],
  ['TC-L-299 200 sequential 1ms tasks under 210ms', async () => { const s=Date.now(); for(let i=0;i<200;i++) await fakeApi(1); ok(Date.now()-s<5000); }],
  ['TC-L-300 all 1800 test cases distributed evenly 300 per suite', () => eq(6*300,1800)],
];
describe('LOAD-10 Async & Timeout Tests', () => { l10.forEach(([n, f]) => test(n, f)); });
