export const TOP_INDIAN_BANKS = [
  'State Bank of India (SBI)',
  'HDFC Bank',
  'ICICI Bank',
  'Punjab National Bank (PNB)',
  'Bank of Baroda (BOB)',
  'Canara Bank',
  'Union Bank of India',
  'Axis Bank',
  'Kotak Mahindra Bank',
  'Indian Bank',
  'Bank of India (BOI)',
];

export const ALL_INDIAN_BANKS = [
  'State Bank of India (SBI)',
  'HDFC Bank',
  'ICICI Bank',
  'Punjab National Bank (PNB)',
  'Bank of Baroda (BOB)',
  'Canara Bank',
  'Union Bank of India',
  'Axis Bank',
  'Kotak Mahindra Bank',
  'IndusInd Bank',
  'Indian Bank',
  'Bank of India (BOI)',
  'Central Bank of India',
  'Indian Overseas Bank (IOB)',
  'UCO Bank',
  'Bank of Maharashtra',
  'Punjab & Sind Bank',
  'YES Bank',
  'IDBI Bank',
  'Federal Bank',
  'IDFC FIRST Bank',
  'Bandhan Bank',
  'Karur Vysya Bank',
  'South Indian Bank',
  'RBL Bank',
  'Jammu & Kashmir Bank',
  'City Union Bank',
  'Karnataka Bank',
  'Tamilnad Mercantile Bank',
  'Dhanlaxmi Bank',
  'CSB Bank',
  'Andhra Pradesh Grameena Vikas Bank',
  'Telangana Grameena Bank',
  'Maharashtra Gramin Bank',
  'Kerala Gramin Bank',
  'Karnataka Gramin Bank',
  'Baroda UP Bank',
  'Aryavart Bank',
  'Prathama UP Gramin Bank',
  'India Post Payments Bank (IPPB)',
  'Paytm Payments Bank',
  'Airtel Payments Bank',
  'Fino Payments Bank',
  'AU Small Finance Bank',
  'Equitas Small Finance Bank',
  'Ujjivan Small Finance Bank',
  'Capital Small Finance Bank',
  'Jana Small Finance Bank',
  'Other / Local Co-operative Bank',
];
