import { Scheme, Category, Notification, User, Application, Ticket, Message, OnboardingItem } from '@/types';

export const onboardingData: OnboardingItem[] = [
  {
    id: '1',
    title: 'Discover Government Schemes',
    description: 'Find all government schemes and services in one place. From education to healthcare, discover benefits tailored for you.',
    image: 'https://images.pexels.com/photos/669622/pexels-photo-669622.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '2',
    title: 'AI-Powered Recommendations',
    description: 'Our smart AI analyzes your profile and suggests the most relevant schemes you are eligible for.',
    image: 'https://images.pexels.com/photos/838644/pexels-photo-838644.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '3',
    title: 'Easy Application Process',
    description: 'Apply for schemes with a simple step-by-step process. Track your applications in real-time.',
    image: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
];

export const languages = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'hi', name: 'Hindi', native: 'हिंदी' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
];

export const categories: Category[] = [
  {
    id: '1',
    name: 'Education',
    icon: 'GraduationCap',
    color: '#2563EB',
    count: 45,
  },
  {
    id: '2',
    name: 'Healthcare',
    icon: 'Heart',
    color: '#EF4444',
    count: 32,
  },
  {
    id: '3',
    name: 'Agriculture',
    icon: 'Leaf',
    color: '#10B981',
    count: 28,
  },
  {
    id: '4',
    name: 'Employment',
    icon: 'Briefcase',
    color: '#F59E0B',
    count: 52,
  },
  {
    id: '5',
    name: 'Women & Child',
    icon: 'Users',
    color: '#EC4899',
    count: 38,
  },
  {
    id: '6',
    name: 'Senior Citizens',
    icon: 'UserCheck',
    color: '#8B5CF6',
    count: 24,
  },
  {
    id: '7',
    name: 'Housing',
    icon: 'Home',
    color: '#06B6D4',
    count: 19,
  },
  {
    id: '8',
    name: 'Finance',
    icon: 'Wallet',
    color: '#84CC16',
    count: 41,
  },
];

export const schemes: Scheme[] = [
  {
    id: '1',
    name: 'PM Vishwakarma Yojana 2026',
    description: 'Recognition, skill training, toolkit and collateral-free loan up to Rs 3 lakh for traditional artisans and craftspeople.',
    category: 'Skills & Employment',
    ministry: 'Ministry of MSME',
    benefits: 'Loan up to Rs 3 lakh + toolkit',
    eligibility: [
      'Traditional artisan/craftsperson',
      'Indian citizen',
      'Age 18+',
      'No government employee in family',
    ],
    documents: ['Aadhaar Card', 'Bank Passbook', 'Mobile number'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 23450,
    featured: true,
    image: 'https://images.pexels.com/photos/4226140/pexels-photo-4226140.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '2',
    name: 'PM-Kisan 23rd Installment 2026',
    description: 'Direct income support of Rs 6,000/year to landholding farmer families. 23rd installment disbursed June 2026.',
    category: 'Agriculture',
    ministry: 'Ministry of Agriculture',
    benefits: 'Rs 6,000 per year',
    eligibility: [
      'Landholding farmer',
      'Indian citizen',
      'Not an institutional landholder',
      'e-KYC completed',
    ],
    documents: ['Aadhaar Card', 'Land Records', 'Bank Passbook'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 125000,
    featured: true,
    image: 'https://images.pexels.com/photos/2165759/pexels-photo-2165759.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '3',
    name: 'Ayushman Bharat PMJAY 2026 Expansion',
    description: 'Health insurance cover of Rs 5 lakh per family per year, now expanded to cover all senior citizens aged 70+ regardless of income.',
    category: 'Healthcare',
    ministry: 'Ministry of Health',
    benefits: 'Rs 5 lakh health coverage',
    eligibility: [
      'Indian citizen',
      'Family listed in SECC or aged 70+',
      'No government employee in family',
    ],
    documents: ['Aadhaar Card', 'Ration Card', 'Address Proof'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 89340,
    featured: true,
    image: 'https://images.pexels.com/photos/236380/pexels-photo-236380.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '4',
    name: 'PM Awas Yojana-Urban 2.0 2026',
    description: 'Affordable housing with interest subsidy up to Rs 2.67 lakh for EWS/LIG/MIG families in urban areas.',
    category: 'Housing',
    ministry: 'Ministry of Housing',
    benefits: 'Subsidy up to Rs 2.67 lakh',
    eligibility: [
      'Annual family income below Rs 18 lakh',
      'No pucca house owned',
      'First-time home buyer',
      'Indian citizen',
    ],
    documents: ['Aadhaar Card', 'Income Certificate', 'Address Proof', 'Bank Passbook'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 98720,
    featured: true,
    image: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '5',
    name: 'Sukanya Samriddhi Yojana 2026',
    description: 'Savings scheme for girl child with 8.2% interest rate and tax benefits under Sec 80C.',
    category: 'Social Security',
    ministry: 'Ministry of Finance',
    benefits: '8.2% interest rate',
    eligibility: [
      'Girl child below 10 years',
      'Indian citizen',
      'Single account per girl',
      'Minimum deposit Rs 250/year',
    ],
    documents: ['Birth Certificate', 'Aadhaar Card', 'Guardian ID'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 45670,
    featured: false,
    image: 'https://images.pexels.com/photos/1128789/pexels-photo-1128789.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '6',
    name: 'National Scholarship Portal 2026-27',
    description: 'Fresh scholarships for post-matric students from minority, SC/ST, and OBC categories for academic year 2026-27.',
    category: 'Education',
    ministry: 'Ministry of Education',
    benefits: 'Up to Rs 50,000 per year',
    eligibility: [
      'Family income below Rs 4.5 lakh',
      'Minimum 50% marks',
      'Indian citizen',
      'Studying at recognized institution',
    ],
    documents: ['Aadhaar Card', 'Income Certificate', 'Marksheet', 'Institution Certificate'],
    deadline: '2026-10-31',
    status: 'active',
    applied: 15420,
    featured: true,
    image: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '7',
    name: 'Stand-Up India 2026',
    description: 'Bank loans between Rs 10 lakh and Rs 1 crore for SC/ST and women entrepreneurs setting up greenfield enterprises.',
    category: 'Business & Startup',
    ministry: 'Ministry of Finance',
    benefits: 'Loan up to Rs 1 crore',
    eligibility: [
      'SC/ST or woman entrepreneur',
      'First-time borrower',
      'Greenfield enterprise',
      'Age 18+',
    ],
    documents: ['Aadhaar Card', 'Business Plan', 'Project Report', 'Bank Passbook'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 33120,
    featured: true,
    image: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '8',
    name: 'PM Surya Ghar Muft Bijli Yojana 2026',
    description: 'Rooftop solar installation with up to 300 units of free electricity per month and 60% subsidy for households.',
    category: 'Environment',
    ministry: 'Ministry of Power',
    benefits: '300 units free electricity + 60% subsidy',
    eligibility: [
      'Household with valid roof',
      'Aadhaar-linked electricity connection',
      'Indian citizen',
    ],
    documents: ['Aadhaar Card', 'Electricity Bill', 'Property Proof', 'Bank Passbook'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 41280,
    featured: true,
    image: 'https://images.pexels.com/photos/371900/pexels-photo-371900.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '9',
    name: 'MUDRA Loan 2026',
    description: 'Collateral-free micro loans up to Rs 10 lakh for small businesses in manufacturing, trading, and services.',
    category: 'Finance',
    ministry: 'Ministry of Finance',
    benefits: 'Loan up to Rs 10 lakh',
    eligibility: [
      'Small business owner',
      'Non-farming activity',
      'Indian citizen',
      'Age 18+',
    ],
    documents: ['Aadhaar Card', 'Business Registration', 'Bank Statement'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 67320,
    featured: false,
    image: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '10',
    name: 'Post-Matric Scholarship for Students with Disabilities 2026',
    description: 'Financial assistance for students with benchmark disabilities pursuing post-matric studies.',
    category: 'Education',
    ministry: 'Ministry of Social Justice',
    benefits: 'Up to Rs 25,000 per year',
    eligibility: [
      '40% or more benchmark disability',
      'Family income below Rs 6 lakh',
      'Indian citizen',
    ],
    documents: ['Disability Certificate', 'Income Certificate', 'Marksheet', 'Aadhaar Card'],
    deadline: '2026-10-31',
    status: 'active',
    applied: 12450,
    featured: false,
    image: 'https://images.pexels.com/photos/256541/pexels-photo-256541.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '11',
    name: 'PM Laghu Vyapari Maan-Dhan Yojana 2026',
    description: 'Pension scheme for small traders and shopkeepers aged 18-40, providing Rs 3,000/month after age 60.',
    category: 'Social Security',
    ministry: 'Ministry of Labour',
    benefits: 'Rs 3,000/month pension',
    eligibility: [
      'Age 18-40 years',
      'Small trader/shopkeeper',
      'Annual turnover below Rs 1.5 crore',
      'Not an income taxpayer',
    ],
    documents: ['Aadhaar Card', 'Bank Passbook', 'GST/Self Declaration'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 18900,
    featured: false,
    image: 'https://images.pexels.com/photos/259132/pexels-photo-259132.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '12',
    name: 'Skill India Digital Hub 2026',
    description: 'Free online skill training and certification in AI, cybersecurity, and digital marketing with job placement support.',
    category: 'Digital Infrastructure',
    ministry: 'Ministry of Skill Development',
    benefits: 'Free training + certification',
    eligibility: [
      'Age 18-45',
      'Indian citizen',
      'Basic digital literacy',
    ],
    documents: ['Aadhaar Card', 'Education Certificate', 'Mobile number'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 56890,
    featured: true,
    image: 'https://images.pexels.com/photos/1181271/pexels-photo-1181271.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
];

export const notifications: Notification[] = [
  {
    id: '1',
    title: 'Application Approved',
    message: 'Your PM Scholarship application has been approved. Funds will be disbursed within 7 days.',
    type: 'success',
    read: false,
    createdAt: '2024-01-15T10:30:00Z',
    schemeId: '1',
  },
  {
    id: '2',
    title: 'Documents Required',
    message: 'Please upload your income certificate to complete your Ayushman Bharat application.',
    type: 'warning',
    read: false,
    createdAt: '2024-01-14T14:20:00Z',
    schemeId: '2',
  },
  {
    id: '3',
    title: 'New Scheme Launched',
    message: 'PM Vishwakarma Yojana is now available. Register now for skill training and credit support.',
    type: 'info',
    read: true,
    createdAt: '2024-01-13T09:00:00Z',
    schemeId: '8',
  },
  {
    id: '4',
    title: 'Deadline Approaching',
    message: 'Your PM Kisan application deadline is in 3 days. Complete your application now.',
    type: 'warning',
    read: false,
    createdAt: '2024-01-12T11:45:00Z',
    schemeId: '3',
  },
  {
    id: '5',
    title: 'Payment Received',
    message: 'INR 2,000 credited to your account for PM Kisan Samman Nidhi installment.',
    type: 'success',
    read: true,
    createdAt: '2024-01-10T16:00:00Z',
    schemeId: '3',
  },
];

export const currentUser: User = {
  id: '1',
  name: 'Rahul Kumar',
  email: 'rahul.kumar@email.com',
  phone: '+91 98765 43210',
  avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=400',
  aadhaar: 'XXXX-XXXX-1234',
  dateOfBirth: '1995-05-15',
  gender: 'Male',
  address: {
    street: '123, Gandhi Road',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110001',
  },
  bankDetails: {
    accountNumber: 'XXXXXXXX1234',
    ifscCode: 'SBIN0001234',
    bankName: 'State Bank of India',
  },
  income: {
    annual: 450000,
    category: 'General',
    source: 'Salaried',
  },
  createdAt: '2023-06-15T08:00:00Z',
};

export const applications: Application[] = [
  {
    id: '1',
    schemeId: '1',
    schemeName: 'PM Vishwakarma Yojana 2026',
    userId: '1',
    status: 'approved',
    currentStep: 6,
    totalSteps: 6,
    submittedAt: '2026-07-05T10:00:00Z',
    updatedAt: '2026-07-20T14:10:00Z',
    documents: [
      { name: 'Aadhaar Card', uploaded: true, verified: true },
      { name: 'Bank Passbook', uploaded: true, verified: true },
    ],
  },
  {
    id: '2',
    schemeId: '3',
    schemeName: 'Ayushman Bharat PMJAY 2026 Expansion',
    userId: '1',
    status: 'submitted',
    currentStep: 4,
    totalSteps: 6,
    submittedAt: '2026-07-10T14:30:00Z',
    updatedAt: '2026-07-15T16:45:00Z',
    documents: [
      { name: 'Aadhaar Card', uploaded: true, verified: true },
      { name: 'Ration Card', uploaded: true, verified: false },
    ],
  },
  {
    id: '3',
    schemeId: '6',
    schemeName: 'National Scholarship Portal 2026-27',
    userId: '1',
    status: 'draft',
    currentStep: 2,
    totalSteps: 6,
    submittedAt: '2026-07-18T09:00:00Z',
    updatedAt: '2026-07-19T11:00:00Z',
    documents: [
      { name: 'Aadhaar Card', uploaded: true, verified: true },
      { name: 'Income Certificate', uploaded: false, verified: false },
    ],
  },
  {
    id: '4',
    schemeId: '7',
    schemeName: 'Stand-Up India 2026',
    userId: '1',
    status: 'submitted',
    currentStep: 5,
    totalSteps: 6,
    submittedAt: '2026-07-08T12:00:00Z',
    updatedAt: '2026-07-12T08:20:00Z',
    documents: [
      { name: 'Aadhaar Card', uploaded: true, verified: true },
      { name: 'Business Plan', uploaded: true, verified: true },
      { name: 'Project Report', uploaded: true, verified: false },
    ],
  },
];

export const tickets: Ticket[] = [
  {
    id: 'TKT001',
    subject: 'Application Status Query',
    description: 'I submitted my application 2 weeks ago but haven\'t received any update.',
    status: 'open',
    priority: 'medium',
    createdAt: '2024-01-14T10:00:00Z',
    updatedAt: '2024-01-14T10:00:00Z',
    responses: [
      {
        id: '1',
        message: 'Thank you for contacting us. We are looking into your concern.',
        sender: 'support',
        timestamp: '2024-01-14T11:30:00Z',
      },
    ],
  },
  {
    id: 'TKT002',
    subject: 'Document Upload Issue',
    description: 'Unable to upload my income certificate. It shows file size error.',
    status: 'resolved',
    priority: 'high',
    createdAt: '2024-01-10T14:00:00Z',
    updatedAt: '2024-01-11T09:00:00Z',
    responses: [
      {
        id: '1',
        message: 'Please ensure the file size is below 2MB and in PDF or JPG format.',
        sender: 'support',
        timestamp: '2024-01-10T15:00:00Z',
      },
      {
        id: '2',
        message: 'Thank you, the issue is resolved now.',
        sender: 'user',
        timestamp: '2024-01-11T09:00:00Z',
      },
    ],
  },
];

export const chatMessages: Message[] = [
  {
    id: '1',
    content: 'Hello! I\'m your AI assistant. How can I help you find the right government scheme today?',
    sender: 'ai',
    timestamp: new Date().toISOString(),
    suggestions: ['Find schemes for education', 'Check my eligibility', 'Track my applications'],
  },
];

export const aiResponses = {
  greeting: 'Hello! I can help you discover government schemes tailored to your needs. What are you looking for?',
  education: 'Based on your profile, here are the top education schemes you may be eligible for:\n\n1. PM Scholarship Scheme - Up to INR 50,000/year\n2. National Fellowship - Full tuition coverage\n3. Education Loan Subsidy - Lower interest rates',
  healthcare: 'Here are healthcare schemes matching your criteria:\n\n1. Ayushman Bharat - INR 5 lakh coverage\n2. PMJAY - Cashless hospitalization\n3. State Health Scheme - Free checkups',
  eligibility: 'To check your eligibility, I\'ll need some information. Let me ask you a few questions:',
  track: 'You have 3 active applications:\n\n1. PM Scholarship - Approved\n2. Ayushman Bharat - In Review\n3. PM Kisan - Pending Documents',
  default: 'I understand you\'re looking for information. Could you be more specific? I can help you with:\n\n• Finding schemes by category\n• Checking eligibility\n• Application status\n• Document requirements',
};

export const FAQs = [
  {
    id: '1',
    question: 'How do I check my eligibility for a scheme?',
    answer: 'You can use our AI-powered eligibility checker. Go to any scheme detail page and tap "Check Eligibility" or use the AI Assistant to get personalized recommendations.',
  },
  {
    id: '2',
    question: 'What documents are required for applying?',
    answer: 'Document requirements vary by scheme. Common documents include Aadhaar Card, Income Certificate, Address Proof, and Bank Passbook. Check the specific scheme page for details.',
  },
  {
    id: '3',
    question: 'How long does the application process take?',
    answer: 'Application processing time varies by scheme. Most schemes take 15-30 days for verification. You can track your application status in real-time from the app.',
  },
  {
    id: '4',
    question: 'Can I edit my application after submission?',
    answer: 'Minor edits can be made within 24 hours of submission. For major changes, you\'ll need to contact support or submit a new application.',
  },
  {
    id: '5',
    question: 'How do I upload documents?',
    answer: 'You can upload documents in PDF, JPG, or PNG format. Maximum file size is 2MB per document. Use the Document Upload section in the application flow.',
  },
  {
    id: '6',
    question: 'What if my application is rejected?',
    answer: 'If your application is rejected, you\'ll receive a notification with the reason. You can address the issues and reapply or contact support for assistance.',
  },
  {
    id: '7',
    question: 'How do I update my profile information?',
    answer: 'Go to Profile > Personal Information to update your details. Some information like Aadhaar cannot be changed directly and may require support assistance.',
  },
  {
    id: '8',
    question: 'Is my data secure?',
    answer: 'Yes, your data is encrypted and stored securely. We follow government data protection guidelines and never share your information without consent.',
  },
];
