import { Scheme, Category, Notification, User, Application, Ticket, Message, OnboardingItem } from '@/types';

export const onboardingData: OnboardingItem[] = [
  {
    id: '1',
    title: 'Discover Government Schemes',
    description: 'Find all government schemes and services in one place. From education to healthcare, discover benefits tailored for you.',
    image: 'https://images.pexels.com/photos/669622/pexels-photo-669622.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '2',
    title: 'AI-Powered Recommendations',
    description: 'Our smart AI analyzes your profile and suggests the most relevant schemes you are eligible for.',
    image: 'https://images.pexels.com/photos/838644/pexels-photo-838644.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '3',
    title: 'Easy Application Process',
    description: 'Apply for schemes with a simple step-by-step process. Track your applications in real-time.',
    image: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
];

export const languages = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'hi', name: 'Hindi', native: 'हिंदी' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
];

export const categories: Category[] = [
  {
    id: '1',
    name: 'Education',
    icon: 'GraduationCap',
    color: '#2563EB',
    count: 45,
  },
  {
    id: '2',
    name: 'Healthcare',
    icon: 'Heart',
    color: '#EF4444',
    count: 32,
  },
  {
    id: '3',
    name: 'Agriculture',
    icon: 'Leaf',
    color: '#10B981',
    count: 28,
  },
  {
    id: '4',
    name: 'Employment',
    icon: 'Briefcase',
    color: '#F59E0B',
    count: 52,
  },
  {
    id: '5',
    name: 'Women & Child',
    icon: 'Users',
    color: '#EC4899',
    count: 38,
  },
  {
    id: '6',
    name: 'Senior Citizens',
    icon: 'UserCheck',
    color: '#8B5CF6',
    count: 24,
  },
  {
    id: '7',
    name: 'Housing',
    icon: 'Home',
    color: '#06B6D4',
    count: 19,
  },
  {
    id: '8',
    name: 'Finance',
    icon: 'Wallet',
    color: '#84CC16',
    count: 41,
  },
];

export const schemes: Scheme[] = [
  {
    id: '1',
    name: 'PM Vishwakarma Yojana 2026',
    description: 'Recognition, skill training, toolkit and collateral-free loan up to Rs 3 lakh for traditional artisans and craftspeople.',
    category: 'Skills & Employment',
    ministry: 'Ministry of MSME',
    benefits: 'Loan up to Rs 3 lakh + toolkit',
    eligibility: [
      'Traditional artisan/craftsperson',
      'Indian citizen',
      'Age 18+',
      'No government employee in family',
    ],
    documents: ['Aadhaar Card', 'Bank Passbook', 'Artisan / Skill Certificate'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 23450,
    featured: true,
    state: 'All India (Central)',
    image: 'https://images.pexels.com/photos/4226140/pexels-photo-4226140.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://pmvishwakarma.gov.in',
  },
  {
    id: '2',
    name: 'PM-Kisan 23rd Installment 2026',
    description: 'Direct income support of Rs 6,000/year to landholding farmer families. 23rd installment disbursed June 2026.',
    category: 'Agriculture',
    ministry: 'Ministry of Agriculture',
    benefits: 'Rs 6,000 per year',
    eligibility: [
      'Landholding farmer',
      'Indian citizen',
      'Not an institutional landholder',
      'e-KYC completed',
    ],
    documents: ['Aadhaar Card', 'Land Records', 'Bank Passbook'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 125000,
    featured: true,
    state: 'All India (Central)',
    image: 'https://images.pexels.com/photos/2165759/pexels-photo-2165759.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://pmkisan.gov.in',
  },
  {
    id: '3',
    name: 'Ayushman Bharat PMJAY 2026 Expansion',
    description: 'Health insurance cover of Rs 5 lakh per family per year, now expanded to cover all senior citizens aged 70+ regardless of income.',
    category: 'Healthcare',
    ministry: 'Ministry of Health',
    benefits: 'Rs 5 lakh health coverage',
    eligibility: [
      'Indian citizen',
      'Family listed in SECC or aged 70+',
      'No government employee in family',
    ],
    documents: ['Aadhaar Card', 'Ration Card', 'Address Proof'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 89340,
    featured: true,
    state: 'All India (Central)',
    image: 'https://images.pexels.com/photos/236380/pexels-photo-236380.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://beneficiary.nha.gov.in',
  },
  {
    id: '4',
    name: 'PM Awas Yojana-Urban 2.0 2026',
    description: 'Affordable housing with interest subsidy up to Rs 2.67 lakh for EWS/LIG/MIG families in urban areas.',
    category: 'Housing',
    ministry: 'Ministry of Housing',
    benefits: 'Subsidy up to Rs 2.67 lakh',
    eligibility: [
      'Annual family income below Rs 18 lakh',
      'No pucca house owned',
      'First-time home buyer',
      'Indian citizen',
    ],
    documents: ['Aadhaar Card', 'Income Certificate', 'Address Proof', 'Bank Passbook'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 98720,
    featured: true,
    state: 'All India (Central)',
    image: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://pmaymis.gov.in',
  },
  {
    id: '5',
    name: 'Sukanya Samriddhi Yojana 2026',
    description: 'Savings scheme for girl child with 8.2% interest rate and tax benefits under Sec 80C.',
    category: 'Social Security',
    ministry: 'Ministry of Finance',
    benefits: '8.2% interest rate',
    eligibility: [
      'Girl child below 10 years',
      'Indian citizen',
      'Single account per girl',
      'Minimum deposit Rs 250/year',
    ],
    documents: ['Birth Certificate', 'Aadhaar Card', 'Guardian ID'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 45670,
    featured: false,
    state: 'All India (Central)',
    image: 'https://images.pexels.com/photos/1128789/pexels-photo-1128789.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://www.indiapost.gov.in/Financial/pages/content/post-office-saving-schemes.aspx',
  },
  {
    id: '6',
    name: 'National Scholarship Portal 2026-27',
    description: 'Fresh scholarships for post-matric students from minority, SC/ST, and OBC categories for academic year 2026-27.',
    category: 'Education',
    ministry: 'Ministry of Education',
    benefits: 'Up to Rs 50,000 per year',
    eligibility: [
      'Family income below Rs 4.5 lakh',
      'Minimum 50% marks',
      'Indian citizen',
      'Studying at recognized institution',
    ],
    documents: ['Aadhaar Card', 'Income Certificate', 'Marksheet', 'Institution Certificate'],
    deadline: '2026-11-30',
    status: 'active',
    applied: 15420,
    featured: true,
    state: 'All India (Central)',
    image: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://scholarships.gov.in',
  },
  {
    id: '7',
    name: 'Stand-Up India 2026',
    description: 'Bank loans between Rs 10 lakh and Rs 1 crore for SC/ST and women entrepreneurs setting up greenfield enterprises.',
    category: 'Business & Startup',
    ministry: 'Ministry of Finance',
    benefits: 'Loan up to Rs 1 crore',
    eligibility: [
      'SC/ST or woman entrepreneur',
      'First-time borrower',
      'Greenfield enterprise',
      'Age 18+',
    ],
    documents: ['Aadhaar Card', 'Business Plan', 'Project Report', 'Bank Passbook'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 33120,
    featured: true,
    state: 'All India (Central)',
    image: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://www.standupmitra.in',
  },
  {
    id: '8',
    name: 'PM Surya Ghar Muft Bijli Yojana 2026',
    description: 'Rooftop solar installation with up to 300 units of free electricity per month and 60% subsidy for households.',
    category: 'Environment',
    ministry: 'Ministry of Power',
    benefits: '300 units free electricity + 60% subsidy',
    eligibility: [
      'Household with valid roof',
      'Aadhaar-linked electricity connection',
      'Indian citizen',
    ],
    documents: ['Aadhaar Card', 'Electricity Bill', 'Property Proof', 'Bank Passbook'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 41280,
    featured: true,
    state: 'All India (Central)',
    image: 'https://images.pexels.com/photos/371900/pexels-photo-371900.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://pmsurya.gov.in',
  },
  {
    id: '9',
    name: 'MUDRA Loan 2026',
    description: 'Collateral-free micro loans up to Rs 10 lakh for small businesses in manufacturing, trading, and services.',
    category: 'Finance',
    ministry: 'Ministry of Finance',
    benefits: 'Loan up to Rs 10 lakh',
    eligibility: [
      'Small business owner',
      'Non-farming activity',
      'Indian citizen',
      'Age 18+',
    ],
    documents: ['Aadhaar Card', 'Business Registration', 'Bank Statement'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 67320,
    featured: false,
    state: 'All India (Central)',
    image: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://www.mudra.org.in',
  },
  {
    id: '10',
    name: 'Rythu Bandhu Scheme 2026 (Telangana)',
    description: 'Investment support scheme for agriculture and horticulture crops by Telangana State Government providing ₹10,000 per acre per year.',
    category: 'Agriculture',
    ministry: 'Dept of Agriculture, Telangana',
    benefits: '₹10,000 per acre per year',
    eligibility: [
      'Telangana State Domicile',
      'Landholding Farmer',
      'Pattadar Passbook Owner',
    ],
    documents: ['Pattadar Passbook', 'Aadhaar Card', 'Telangana Bank Passbook'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 64200,
    featured: true,
    state: 'Telangana',
    image: 'https://images.pexels.com/photos/2165759/pexels-photo-2165759.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://rythubandhu.telangana.gov.in',
  },
  {
    id: '11',
    name: 'YSR Amma Vodi Scheme 2026 (Andhra Pradesh)',
    description: 'Financial assistance of ₹15,000 per year to mothers below poverty line for sending their children to school.',
    category: 'Education',
    ministry: 'Dept of School Education, Andhra Pradesh',
    benefits: '₹15,000 per year',
    eligibility: [
      'Andhra Pradesh Domicile',
      'Mother / Guardian of school student (Class 1 to 12)',
      'BPL Household',
    ],
    documents: ['Aadhaar Card', 'White Ration Card', 'Student School Id', 'Bank Account'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 82100,
    featured: true,
    state: 'Andhra Pradesh',
    image: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://ysrammavodi.ap.gov.in',
  },
  {
    id: '12',
    name: 'Mukhyamantri Majhi Ladki Bahin Yojana 2026 (Maharashtra)',
    description: 'Financial assistance of ₹1,500 per month directly credited to women in Maharashtra aged 21-65 years.',
    category: 'Women & Child',
    ministry: 'Women and Child Development, Maharashtra',
    benefits: '₹1,500 per month cash support',
    eligibility: [
      'Maharashtra Resident',
      'Women aged 21 to 65 years',
      'Annual family income < ₹2.5 Lakh',
    ],
    documents: ['Aadhaar Card', 'Maharashtra Domicile Certificate', 'Ration Card', 'Bank Passbook'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 114000,
    featured: true,
    state: 'Maharashtra',
    image: 'https://images.pexels.com/photos/1181271/pexels-photo-1181271.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://ladakibahin.maharashtra.gov.in',
  },
  {
    id: '13',
    name: 'Gruha Lakshmi Scheme 2026 (Karnataka)',
    description: 'Monthly assistance of ₹2,000 for women head of the family in Karnataka.',
    category: 'Social Security',
    ministry: 'Women and Child Development, Karnataka',
    benefits: '₹2,000 per month',
    eligibility: [
      'Karnataka Domicile',
      'Woman declared as Head of Family in Ration Card',
      'Non-taxpayer family',
    ],
    documents: ['Ration Card (BPL/APL)', 'Aadhaar Card', 'Bank Passbook'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 94500,
    featured: true,
    state: 'Karnataka',
    image: 'https://images.pexels.com/photos/259132/pexels-photo-259132.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://sevasindhu.karnataka.gov.in',
  },
  {
    id: '14',
    name: 'Kalaignar Magalir Urimai Thittam 2026 (Tamil Nadu)',
    description: 'Rights grant of ₹1,000 per month to eligible women family heads across Tamil Nadu.',
    category: 'Women & Child',
    ministry: 'Social Welfare Dept, Tamil Nadu',
    benefits: '₹1,000 per month',
    eligibility: [
      'Tamil Nadu Resident',
      'Woman Head of Household aged 21+',
      'Family income below ₹2.5 Lakh/year',
    ],
    documents: ['Smart Ration Card', 'Aadhaar Card', 'Electricity Bill', 'Bank Passbook'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 102300,
    featured: true,
    state: 'Tamil Nadu',
    image: 'https://images.pexels.com/photos/1181271/pexels-photo-1181271.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://www.tn.gov.in/scheme/data_view/16849',
  },
  {
    id: '15',
    name: 'Kanya Sumangala Yojana 2026 (Uttar Pradesh)',
    description: 'Financial grant up to ₹25,000 in six installments for girl child education and health in Uttar Pradesh.',
    category: 'Women & Child',
    ministry: 'Women and Child Development, Uttar Pradesh',
    benefits: 'Up to ₹25,000 total grant',
    eligibility: [
      'Uttar Pradesh Resident',
      'Family income < ₹3 Lakh/year',
      'Maximum 2 girls per family',
    ],
    documents: ['UP Domicile Certificate', 'Birth Certificate', 'Income Proof', 'Aadhaar'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 78900,
    featured: true,
    state: 'Uttar Pradesh',
    image: 'https://images.pexels.com/photos/1128789/pexels-photo-1128789.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://mksy.up.gov.in',
  },
  {
    id: '16',
    name: 'Kanyashree Prakalpa 2026 (West Bengal)',
    description: 'Conditional cash transfer scheme for improving the status and education of girl students in West Bengal.',
    category: 'Education',
    ministry: 'Dept of Women & Child Development, West Bengal',
    benefits: '₹1,000 annual scholarship + ₹25,000 one-time grant',
    eligibility: [
      'West Bengal Resident',
      'Girl student aged 13-18 enrolled in school/college',
      'Unmarried',
    ],
    documents: ['WB Domicile Proof', 'School Headmaster Certificate', 'Bank Account', 'Aadhaar'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 88400,
    featured: true,
    state: 'West Bengal',
    image: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://wbkanyashree.gov.in',
  },
  {
    id: '17',
    name: 'Mukhyamantri Teerth Yatra Yojana 2026 (Delhi)',
    description: 'Free pilgrimage trips for senior citizens of Delhi with complete travel, lodging, and food covered by Delhi Govt.',
    category: 'Senior Citizens',
    ministry: 'Revenue Dept, Delhi Govt',
    benefits: '100% Free Pilgrimage Trip',
    eligibility: [
      'Delhi Domicile',
      'Senior Citizen aged 60+ years',
      'No income criteria',
    ],
    documents: ['Delhi Voter ID / Aadhaar', 'Medical Fitness Certificate'],
    deadline: '2026-12-31',
    status: 'active',
    applied: 31200,
    featured: true,
    state: 'Delhi',
    image: 'https://images.pexels.com/photos/669622/pexels-photo-669622.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://edistrict.delhigovt.nic.in',
  },
  {
    id: '18',
    name: 'PM Digital Saksharta Abhiyan Phase 2 2026-27',
    description: 'Digital literacy training program for rural households across India. Registrations open for FY 2026-27.',
    category: 'Education',
    ministry: 'Ministry of Electronics & IT',
    benefits: 'Free 20-hour digital skill training',
    eligibility: [
      'Rural household member aged 14-60',
      'Digitally illiterate',
    ],
    documents: ['Aadhaar Card'],
    deadline: '2027-03-31',
    status: 'active',
    applied: 52100,
    featured: false,
    state: 'All India (Central)',
    image: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://www.pmgdisha.in',
  },
  {
    id: '19',
    name: 'National Talent Search Exam (NTSE) 2026-27',
    description: 'National level scholarship exam for Class 10 students for academic session 2026-27.',
    category: 'Education',
    ministry: 'NCERT / Ministry of Education',
    benefits: '₹1,250 per month scholarship',
    eligibility: [
      'Class 10 student',
      'Minimum 60% marks in Class 9',
    ],
    documents: ['Class 9 Marksheet', 'Aadhaar Card', 'School ID'],
    deadline: '2026-11-30',
    status: 'active',
    applied: 43200,
    featured: false,
    state: 'All India (Central)',
    image: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=800',
    officialUrl: 'https://ncert.nic.in',
  },
];

export const notifications: Notification[] = [
  {
    id: '1',
    title: 'Welcome to CitizenAware 2026',
    message: 'Explore over 180+ central and state government schemes tailored for you.',
    type: 'info',
    read: true,
    createdAt: '2026-07-28T10:30:00Z',
    created_at: '2026-07-28T10:30:00Z',
  },
  {
    id: '2',
    title: 'PM Surya Ghar Muft Bijli Yojana 2026',
    message: 'PM Surya Ghar Muft Bijli Yojana 2026 is active. Apply to receive solar panel rooftop subsidies.',
    type: 'info',
    read: true,
    createdAt: '2026-07-25T09:00:00Z',
    created_at: '2026-07-25T09:00:00Z',
    schemeId: '8',
    scheme_id: '8',
  },
];

export const currentUser: User = {
  id: '1',
  name: 'Rahul Kumar',
  email: 'rahul.kumar@email.com',
  phone: '+91 98765 43210',
  avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=400',
  aadhaar: 'XXXX-XXXX-1234',
  dateOfBirth: '1995-05-15',
  gender: 'Male',
  address: {
    street: '123, Gandhi Road',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110001',
  },
  bankDetails: {
    accountNumber: 'XXXXXXXX1234',
    ifscCode: 'SBIN0001234',
    bankName: 'State Bank of India',
  },
  income: {
    annual: 450000,
    category: 'General',
    source: 'Salaried',
  },
  createdAt: '2023-06-15T08:00:00Z',
};

export const applications: Application[] = [
  {
    id: '1',
    schemeId: '1',
    schemeName: 'PM Vishwakarma Yojana 2026',
    userId: '1',
    status: 'approved',
    currentStep: 6,
    totalSteps: 6,
    submittedAt: '2026-07-05T10:00:00Z',
    updatedAt: '2026-07-20T14:10:00Z',
    documents: [
      { name: 'Aadhaar Card', uploaded: true, verified: true },
      { name: 'Bank Passbook', uploaded: true, verified: true },
    ],
  },
  {
    id: '2',
    schemeId: '3',
    schemeName: 'Ayushman Bharat PMJAY 2026 Expansion',
    userId: '1',
    status: 'submitted',
    currentStep: 4,
    totalSteps: 6,
    submittedAt: '2026-07-10T14:30:00Z',
    updatedAt: '2026-07-15T16:45:00Z',
    documents: [
      { name: 'Aadhaar Card', uploaded: true, verified: true },
      { name: 'Ration Card', uploaded: true, verified: false },
    ],
  },
  {
    id: '3',
    schemeId: '6',
    schemeName: 'National Scholarship Portal 2026-27',
    userId: '1',
    status: 'draft',
    currentStep: 2,
    totalSteps: 6,
    submittedAt: '2026-07-18T09:00:00Z',
    updatedAt: '2026-07-19T11:00:00Z',
    documents: [
      { name: 'Aadhaar Card', uploaded: true, verified: true },
      { name: 'Income Certificate', uploaded: false, verified: false },
    ],
  },
  {
    id: '4',
    schemeId: '7',
    schemeName: 'Stand-Up India 2026',
    userId: '1',
    status: 'submitted',
    currentStep: 5,
    totalSteps: 6,
    submittedAt: '2026-07-08T12:00:00Z',
    updatedAt: '2026-07-12T08:20:00Z',
    documents: [
      { name: 'Aadhaar Card', uploaded: true, verified: true },
      { name: 'Business Plan', uploaded: true, verified: true },
      { name: 'Project Report', uploaded: true, verified: false },
    ],
  },
];

export const tickets: Ticket[] = [
  {
    id: 'TKT001',
    subject: 'Application Status Query',
    description: 'I submitted my application 2 weeks ago but haven\'t received any update.',
    status: 'open',
    priority: 'medium',
    createdAt: '2026-07-20T10:00:00Z',
    updatedAt: '2026-07-20T10:00:00Z',
    responses: [
      {
        id: '1',
        message: 'Thank you for contacting us. We are looking into your concern.',
        sender: 'support',
        timestamp: '2026-07-20T11:30:00Z',
      },
    ],
  },
  {
    id: 'TKT002',
    subject: 'Document Upload Issue',
    description: 'Unable to upload my income certificate. It shows file size error.',
    status: 'resolved',
    priority: 'high',
    createdAt: '2026-07-15T14:00:00Z',
    updatedAt: '2026-07-16T09:00:00Z',
    responses: [
      {
        id: '1',
        message: 'Please ensure the file size is below 2MB and in PDF or JPG format.',
        sender: 'support',
        timestamp: '2026-07-15T15:00:00Z',
      },
      {
        id: '2',
        message: 'Thank you, the issue is resolved now.',
        sender: 'user',
        timestamp: '2026-07-16T09:00:00Z',
      },
    ],
  },
];

export const chatMessages: Message[] = [
  {
    id: '1',
    content: 'Hello! I\'m your AI assistant. How can I help you find the right government scheme today?',
    sender: 'ai',
    timestamp: new Date().toISOString(),
    suggestions: ['Find schemes for education', 'Check my eligibility', 'Track my applications'],
  },
];

export const aiResponses = {
  greeting: 'Hello! I am your CitizenAware 2026 AI Assistant. I can help you discover 180+ Central & State government schemes tailored to your needs. What are you looking for?',
  education: 'Based on 2026 academic guidelines, here are top education schemes:\n\n1. National Scholarship Portal 2026-27 - Up to ₹50,000/year\n2. YSR Amma Vodi 2026 - ₹15,000/year for school students\n3. Kanyashree Prakalpa 2026 - ₹25,000 one-time education grant',
  healthcare: 'Here are healthcare schemes for 2026:\n\n1. Ayushman Bharat PMJAY 2026 Expansion - ₹5 Lakh coverage (now free for all seniors 70+)\n2. PM Surakshit Matritva Abhiyan - Free maternal healthcare & diagnostics',
  eligibility: 'To check your eligibility under 2026 guidelines, I can evaluate your state, income, and category. Tap any scheme or ask me!',
  track: 'You have active applications:\n\n1. PM Vishwakarma Yojana 2026 - Approved\n2. Ayushman Bharat 2026 Expansion - Submitted / In Review\n3. National Scholarship Portal 2026-27 - Draft',
  default: 'I can assist you with 2026 parameters for:\n\n• Central & State schemes by category\n• Instant eligibility assessment\n• Document checklists\n• Direct official portal links',
};

export const FAQs = [
  {
    id: '1',
    question: 'How do I check my eligibility for a scheme?',
    answer: 'You can use our AI-powered eligibility checker. Go to any scheme detail page and tap "Check Eligibility" or use the AI Assistant to get personalized recommendations.',
  },
  {
    id: '2',
    question: 'What documents are required for applying?',
    answer: 'Document requirements vary by scheme. Common documents include Aadhaar Card, Income Certificate, Address Proof, and Bank Passbook. Check the specific scheme page for details.',
  },
  {
    id: '3',
    question: 'How long does the application process take?',
    answer: 'Application processing time varies by scheme. Most schemes take 15-30 days for verification. You can track your application status in real-time from the app.',
  },
  {
    id: '4',
    question: 'Can I edit my application after submission?',
    answer: 'Minor edits can be made within 24 hours of submission. For major changes, you\'ll need to contact support or submit a new application.',
  },
  {
    id: '5',
    question: 'How do I upload documents?',
    answer: 'You can upload documents in PDF, JPG, or PNG format. Maximum file size is 2MB per document. Use the Document Upload section in the application flow.',
  },
  {
    id: '6',
    question: 'What if my application is rejected?',
    answer: 'If your application is rejected, you\'ll receive a notification with the reason. You can address the issues and reapply or contact support for assistance.',
  },
  {
    id: '7',
    question: 'How do I update my profile information?',
    answer: 'Go to Profile > Personal Information to update your details. Some information like Aadhaar cannot be changed directly and may require support assistance.',
  },
  {
    id: '8',
    question: 'Is my data secure?',
    answer: 'Yes, your data is encrypted and stored securely. We follow government data protection guidelines and never share your information without consent.',
  },
];
