export const STATE_DISTRICTS_MAP: Record<string, string[]> = {
  'Tamil Nadu': [
    'Ariyalur',
    'Chengalpattu',
    'Chennai',
    'Coimbatore',
    'Cuddalore',
    'Dharmapuri',
    'Dindigul',
    'Erode',
    'Kallakurichi',
    'Kanchipuram',
    'Kanyakumari (Nagercoil)',
    'Karur',
    'Krishnagiri',
    'Madurai',
    'Mayiladuthurai',
    'Nagapattinam',
    'Namakkal',
    'Nilgiris (Udhagamandalam / Ooty)',
    'Perambalur',
    'Pudukkottai',
    'Ramanathapuram',
    'Ranipet',
    'Salem',
    'Sivaganga',
    'Tenkasi',
    'Thanjavur',
    'Theni',
    'Thoothukudi (Tuticorin)',
    'Tiruchirappalli (Trichy)',
    'Tirunelveli',
    'Tirupathur',
    'Tiruppur',
    'Tiruvallur',
    'Tiruvannamalai',
    'Tiruvarur',
    'Vellore',
    'Viluppuram',
    'Virudhunagar',
  ],
  'Telangana': [
    'Adilabad',
    'Bhadradri Kothagudem',
    'Hanamkonda (Warangal Urban)',
    'Hyderabad',
    'Jagtial',
    'Jangaon',
    'Jayashankar Bhupalpally',
    'Jogulamba Gadwal',
    'Kamareddy',
    'Karimnagar',
    'Khammam',
    'Kumuram Bheem Asifabad',
    'Mahabubabad',
    'Mahabubnagar',
    'Mancherial',
    'Medak',
    'Medchal-Malkajgiri',
    'Mulugu',
    'Nagarkurnool',
    'Nalgonda',
    'Narayanpet',
    'Nirmal',
    'Nizamabad',
    'Peddapalli',
    'Rajanna Sircilla',
    'Rangareddy',
    'Sangareddy',
    'Siddipet',
    'Suryapet',
    'Vikarabad',
    'Wanaparthy',
    'Warangal (Warangal Rural)',
    'Yadadri Bhuvanagiri',
  ],
  'Andhra Pradesh': [
    'Alluri Sitharama Raju',
    'Anakapalli',
    'Ananthapuramu',
    'Annamayya',
    'Bapatla',
    'Chittoor',
    'East Godavari (Rajamahendravaram)',
    'Eluru',
    'Guntur',
    'Kakinada',
    'Kona Seema (Amalapuram)',
    'Kurnool',
    'Nandyal',
    'NTR (Vijayawada)',
    'Palnadu (Narasaraopet)',
    'Parvathipuram Manyam',
    'Prakasam (Ongole)',
    'Sri Potti Sriramulu Nellore',
    'Sri Sathya Sai (Puttaparthi)',
    'Srikakulam',
    'Tirupati',
    'Visakhapatnam',
    'Vizianagaram',
    'West Godavari (Bhimavaram)',
    'YSR Kadapa',
  ],
  'Maharashtra': [
    'Ahilyanagar (Ahmednagar)',
    'Akola',
    'Amravati',
    'Beed',
    'Bhandara',
    'Buldhana',
    'Chandrapur',
    'Chhatrapati Sambhajinagar (Aurangabad)',
    'Dhule',
    'Gadchiroli',
    'Gondia',
    'Hingoli',
    'Jalgaon',
    'Jalna',
    'Kolhapur',
    'Latur',
    'Mumbai City',
    'Mumbai Suburban',
    'Nagpur',
    'Nanded',
    'Nandurbar',
    'Nashik',
    'Dharashiv (Osmanabad)',
    'Palghar',
    'Parbhani',
    'Pune',
    'Raigad (Alibag)',
    'Ratnagiri',
    'Sangli',
    'Satara',
    'Sindhudurg',
    'Solapur',
    'Thane',
    'Wardha',
    'Washim',
    'Yavatmal',
  ],
  'Karnataka': [
    'Bagalkote',
    'Ballari',
    'Belagavi',
    'Bengaluru Rural',
    'Bengaluru Urban',
    'Bidar',
    'Chamarajanagara',
    'Chikkaballapura',
    'Chikkamagaluru',
    'Chitradurga',
    'Dakshina Kannada (Mangaluru)',
    'Davanagere',
    'Dharwad (Hubballi)',
    'Gadag',
    'Hassan',
    'Haveri',
    'Kalaburagi',
    'Kodagu (Madikeri)',
    'Kolar',
    'Koppal',
    'Mandya',
    'Mysuru',
    'Raichur',
    'Ramanagara',
    'Shivamogga',
    'Tumakuru',
    'Udupi',
    'Uttara Kannada (Karwar)',
    'Vijayanagara (Hospet)',
    'Vijayapura',
    'Yadgir',
  ],
  'Kerala': [
    'Alappuzha',
    'Ernakulam (Kochi)',
    'Idukki',
    'Kannur',
    'Kasaragod',
    'Kollam',
    'Kottayam',
    'Kozhikode',
    'Malappuram',
    'Palakkad',
    'Pathanamthitta',
    'Thiruvananthapuram',
    'Thrissur',
    'Wayanad',
  ],
  'Uttar Pradesh': [
    'Agra',
    'Aligarh',
    'Ambedkar Nagar',
    'Amethi',
    'Amroha',
    'Auraiya',
    'Ayodhya',
    'Azamgarh',
    'Baghpat',
    'Bahraich',
    'Ballia',
    'Balrampur',
    'Banda',
    'Barabanki',
    'Bareilly',
    'Basti',
    'Bhadohi',
    'Bijnor',
    'Budaun',
    'Bulandshahr',
    'Chandauli',
    'Chitrakoot',
    'Deoria',
    'Etah',
    'Etawah',
    'Farrukhabad',
    'Fatehpur',
    'Firozabad',
    'Gautam Buddha Nagar (Noida)',
    'Ghaziabad',
    'Ghazipur',
    'Gonda',
    'Gorakhpur',
    'Hamirpur',
    'Hapur',
    'Hardoi',
    'Hathras',
    'Jalaun',
    'Jaunpur',
    'Jhansi',
    'Kannauj',
    'Kanpur Dehat',
    'Kanpur Nagar',
    'Kasganj',
    'Kaushambi',
    'Kheri (Lakhimpur)',
    'Kushinagar',
    'Lalitpur',
    'Lucknow',
    'Maharajganj',
    'Mahoba',
    'Mainpuri',
    'Mathura',
    'Mau',
    'Meerut',
    'Mirzapur',
    'Moradabad',
    'Muzaffarnagar',
    'Pilibhit',
    'Pratapgarh',
    'Prayagraj (Allahabad)',
    'Raebareli',
    'Rampur',
    'Saharanpur',
    'Sambhal',
    'Sant Kabir Nagar',
    'Shahjahanpur',
    'Shamli',
    'Shravasti',
    'Siddharthnagar',
    'Sitapur',
    'Sonbhadra',
    'Sultanpur',
    'Unnao',
    'Varanasi',
  ],
  'Gujarat': [
    'Ahmedabad',
    'Amreli',
    'Anand',
    'Aravalli',
    'Banaskantha (Palanpur)',
    'Bharuch',
    'Bhavnagar',
    'Botad',
    'Chhota Udepur',
    'Dahod',
    'Dang (Ahwa)',
    'Devbhumi Dwarka',
    'Gandhinagar',
    'Gir Somnath',
    'Jamnagar',
    'Junagadh',
    'Kheda (Nadiad)',
    'Kutch (Bhuj)',
    'Mahisagar (Lunawada)',
    'Mehsana',
    'Morbi',
    'Narmada (Rajpipla)',
    'Navsari',
    'Panchmahal (Godhra)',
    'Patan',
    'Porbandar',
    'Rajkot',
    'Sabarkantha (Himmatnagar)',
    'Surat',
    'Surendranagar',
    'Tapi (Vyara)',
    'Vadodara',
    'Valsad',
  ],
  'West Bengal': [
    'Alipurduar',
    'Bankura',
    'Birbhum',
    'Cooch Behar',
    'Dakshin Dinajpur (Balurghat)',
    'Darjeeling',
    'Hooghly',
    'Howrah',
    'Jalpaiguri',
    'Jhargram',
    'Kalimpong',
    'Kolkata',
    'Malda',
    'Murshidabad',
    'Nadia',
    'North 24 Parganas (Barasat)',
    'Paschim Bardhaman (Asansol/Durgapur)',
    'Paschim Medinipur (Kharagpur/Midnapore)',
    'Purba Bardhaman',
    'Purba Medinipur (Tamluk)',
    'Purulia',
    'South 24 Parganas (Alipore)',
    'Uttar Dinajpur (Raiganj)',
  ],
  'Rajasthan': [
    'Ajmer',
    'Alwar',
    'Anupgarh',
    'Balotra',
    'Banswara',
    'Baran',
    'Barmer',
    'Beawar',
    'Bharatpur',
    'Bhilwara',
    'Bikaner',
    'Bundi',
    'Chittorgarh',
    'Churu',
    'Dausa',
    'Deeg',
    'Didwana-Kuchaman',
    'Dholpur',
    'Dungarpur',
    'Gangaapur City',
    'Hanumangarh',
    'Jaipur City',
    'Jaipur Rural',
    'Jaisalmer',
    'Jalore',
    'Jhalawar',
    'Jhunjhunu',
    'Jodhpur City',
    'Jodhpur Rural',
    'Karauli',
    'Kekri',
    'Kota',
    'Kotputli-Behror',
    'Khairthal-Tijara',
    'Nagaur',
    'Neem Ka Thana',
    'Pali',
    'Phalodi',
    'Pratapgarh',
    'Rajsamand',
    'Salumbar',
    'Sanchore',
    'Sawai Madhopur',
    'Shahpura',
    'Sikar',
    'Sirohi',
    'Sri Ganganagar',
    'Tonk',
    'Udaipur',
  ],
  'Bihar': [
    'Araria',
    'Arwal',
    'Aurangabad',
    'Banka',
    'Begusarai',
    'Bhagalpur',
    'Bhojpur (Arrah)',
    'Buxar',
    'Darbhanga',
    'East Champaran (Motihari)',
    'Gaya',
    'Gopalganj',
    'Jamui',
    'Jehanabad',
    'Kaimur (Bhabua)',
    'Katihar',
    'Khagaria',
    'Kishanganj',
    'Lakhisarai',
    'Madhepura',
    'Madhubani',
    'Munger',
    'Muzaffarpur',
    'Nalanda (Bihar Sharif)',
    'Nawada',
    'Patna',
    'Purnia',
    'Rohtas (Sasaram)',
    'Saharsa',
    'Samastipur',
    'Saran (Chhapra)',
    'Sheikhpura',
    'Sheohar',
    'Sitamarhi',
    'Siwan',
    'Supaul',
    'Vaishali (Hajipur)',
    'West Champaran (Bettiah)',
  ],
  'Punjab': [
    'Amritsar',
    'Barnala',
    'Bathinda',
    'Faridkot',
    'Fatehgarh Sahib',
    'Fazilka',
    'Firozpur',
    'Gurdaspur',
    'Hoshiarpur',
    'Jalandhar',
    'Kapurthala',
    'Ludhiana',
    'Malerkotla',
    'Mansa',
    'Moga',
    'Muktsar Sahib',
    'Pathankot',
    'Patiala',
    'Rupnagar (Ropar)',
    'SAS Nagar (Mohali)',
    'Sangrur',
    'SBS Nagar (Nawanshahr)',
    'Tarn Taran',
  ],
  'Haryana': [
    'Ambala',
    'Bhiwani',
    'Charkhi Dadri',
    'Faridabad',
    'Fatehabad',
    'Gurugram',
    'Hisar',
    'Jhajjar',
    'Jind',
    'Kaithal',
    'Karnal',
    'Kurukshetra',
    'Mahendragarh (Narnaul)',
    'Nuh (Mewat)',
    'Palwal',
    'Panchkula',
    'Panipat',
    'Rewari',
    'Rohtak',
    'Sirsa',
    'Sonipat',
    'Yamunanagar',
  ],
  'Madhya Pradesh': [
    'Agar Malwa',
    'Alirajpur',
    'Anuppur',
    'Ashoknagar',
    'Balaghat',
    'Barwani',
    'Betul',
    'Bhind',
    'Bhopal',
    'Burhanpur',
    'Chhatarpur',
    'Chhindwara',
    'Damoh',
    'Datia',
    'Dewas',
    'Dhar',
    'Dindori',
    'Guna',
    'Gwalior',
    'Harda',
    'Narmadapuram (Hoshangabad)',
    'Indore',
    'Jabalpur',
    'Jhabua',
    'Katni',
    'Khandwa (East Nimar)',
    'Khargone (West Nimar)',
    'Mandla',
    'Mandsaur',
    'Mauganj',
    'Morena',
    'Narsinghpur',
    'Neemuch',
    'Niwari',
    'Panna',
    'Raisen',
    'Rajgarh',
    'Ratlam',
    'Rewa',
    'Sagar',
    'Satna',
    'Sehore',
    'Seoni',
    'Shahdol',
    'Shajapur',
    'Sheopur',
    'Shivpuri',
    'Sidhi',
    'Singrauli',
    'Tikamgarh',
    'Ujjain',
    'Umaria',
    'Vidisha',
  ],
  'Odisha': [
    'Angul',
    'Balangir',
    'Balasore (Baleswar)',
    'Bargarh',
    'Bhadrak',
    'Baudh',
    'Cuttack',
    'Deogarh',
    'Dhenkanal',
    'Gajapati',
    'Ganjam (Berhampur)',
    'Jagatsinghpur',
    'Jajpur',
    'Jharsuguda',
    'Kalahandi',
    'Kandamahal',
    'Kendrapara',
    'Kendujhar (Keonjhar)',
    'Khurda (Bhubaneswar)',
    'Koraput',
    'Malkangiri',
    'Mayurbhanj (Baripada)',
    'Nabarangpur',
    'Nayagarh',
    'Nuapada',
    'Puri',
    'Rayagada',
    'Sambalpur',
    'Subarnapur (Sonepur)',
    'Sundargarh (Rourkela)',
  ],
  'Assam': [
    'Bajali',
    'Baksa',
    'Barpeta',
    'Biswanath',
    'Bongaigaon',
    'Cachar (Silchar)',
    'Charaideo',
    'Chirang',
    'Darrang',
    'Dhemaji',
    'Dhubri',
    'Dibrugarh',
    'Dima Hasao (Haflong)',
    'Goalpara',
    'Golaghat',
    'Hailakandi',
    'Hojai',
    'Jorhat',
    'Kamrup',
    'Kamrup Metropolitan (Guwahati)',
    'Karbi Anglong',
    'Karimganj',
    'Kokrajhar',
    'Lakhimpur',
    'Majuli',
    'Morigaon',
    'Nagaon',
    'Nalbari',
    'Sivasagar',
    'Sonitpur (Tezpur)',
    'South Salmara-Mankachar',
    'Tinsukia',
    'Udalguri',
    'West Karbi Anglong',
  ],
  'Chhattisgarh': [
    'Balod',
    'Baloda Bazar',
    'Balrampur-Ramanujganj',
    'Bastar (Jagdalpur)',
    'Bemetara',
    'Bijapur',
    'Bilaspur',
    'Dantewada',
    'Dhamtari',
    'Durg (Bhilai)',
    'Gariaband',
    'Gaurela-Pendra-Marwahi',
    'Janjgir-Champa',
    'Jashpur',
    'Kabirdham (Kawardha)',
    'Kanker',
    'Khairagarh-Chhuikhadan-Gandai',
    'Kondagaon',
    'Korba',
    'Koriya',
    'Mahasamund',
    'Manendragarh-Chirmiri-Bharatpur',
    'Mohla-Manpur-Ambagarh Chowki',
    'Mungeli',
    'Narayanpur',
    'Raigarh',
    'Raipur',
    'Rajnandgaon',
    'Sarangarh-Bilaigarh',
    'Sukma',
    'Surajpur',
    'Surguja (Ambikapur)',
  ],
  'Jharkhand': [
    'Bokaro',
    'Chatra',
    'Deoghar',
    'Dhanbad',
    'Dumka',
    'East Singhbhum (Jamshedpur)',
    'Garhwa',
    'Giridih',
    'Godda',
    'Gumla',
    'Hazaribagh',
    'Jamtara',
    'Khunti',
    'Koderma',
    'Latehar',
    'Lohardaga',
    'Pakur',
    'Palamu (Daltonganj)',
    'Ramgarh',
    'Ranchi',
    'Sahibganj',
    'Seraikela Kharsawan',
    'Simdega',
    'West Singhbhum (Chaibasa)',
  ],
  'Delhi': [
    'Central Delhi',
    'East Delhi',
    'New Delhi',
    'North Delhi',
    'North East Delhi',
    'North West Delhi',
    'Shahdara',
    'South Delhi',
    'South East Delhi',
    'South West Delhi',
    'West Delhi',
  ],
  'Uttarakhand': [
    'Almora',
    'Bageshwar',
    'Chamoli (Gopeshwar)',
    'Champawat',
    'Dehradun',
    'Haridwar',
    'Nainital (Haldwani)',
    'Pauri Garhwal (Rishikesh)',
    'Pithoragarh',
    'Rudraprayag',
    'Tehri Garhwal',
    'Udham Singh Nagar (Rudrapur)',
    'Uttarkashi',
  ],
  'Goa': [
    'North Goa (Panaji / Mapusa)',
    'South Goa (Margao / Vasco da Gama)',
  ],
  'Jammu and Kashmir': [
    'Anantnag',
    'Bandipora',
    'Baramulla',
    'Budgam',
    'Doda',
    'Ganderbal',
    'Jammu',
    'Kathua',
    'Kishtwar',
    'Kulgam',
    'Kupwara',
    'Poonch',
    'Pulwama',
    'Rajouri',
    'Ramban',
    'Reasi',
    'Samba',
    'Shopian',
    'Srinagar',
    'Udhampur',
  ],
  'Himachal Pradesh': [
    'Bilaspur',
    'Chamba',
    'Hamirpur',
    'Kangra (Dharamshala)',
    'Kinnaur',
    'Kullu',
    'Lahaul and Spiti',
    'Mandi',
    'Shimla',
    'Sirmaur',
    'Solan',
    'Una',
  ],
  'Puducherry': [
    'Karaikal',
    'Mahe',
    'Puducherry',
    'Yanam',
  ],
  'Chandigarh': [
    'Chandigarh Central',
    'Chandigarh North',
    'Chandigarh South',
  ],
  'Arunachal Pradesh': [
    'Anjaw',
    'Changlang',
    'East Kameng',
    'East Siang (Pasighat)',
    'Itanagar Capital Complex',
    'Kamle',
    'Kra Daadi',
    'Kurung Kumey',
    'Lepa Rada',
    'Lhit',
    'Longding',
    'Lower Dibang Valley',
    'Lower Subansiri (Ziro)',
    'Namsai',
    'Pakke Kessang',
    'Papum Pare',
    'Shi Yomi',
    'Siang',
    'Tawang',
    'Tirap',
    'Upper Dibang Valley',
    'Upper Subansiri',
    'Upper Siang',
    'West Kameng',
    'West Siang',
  ],
  'Meghalaya': [
    'East Garo Hills (Williamnagar)',
    'East Jaintia Hills (Khliehriat)',
    'East Khasi Hills (Shillong)',
    'Eastern West Khasi Hills (Mairang)',
    'North Garo Hills (Resubelpara)',
    'Ri Bhoi (Nongpoh)',
    'South Garo Hills (Baghmara)',
    'South West Garo Hills (Ampati)',
    'South West Khasi Hills (Mawkyrwat)',
    'West Garo Hills (Tura)',
    'West Jaintia Hills (Jowai)',
    'West Khasi Hills (Nongstoin)',
  ],
  'Manipur': [
    'Bishnupur',
    'Chandel',
    'Churachandpur',
    'Imphal East',
    'Imphal West',
    'Jiribam',
    'Kakching',
    'Kamjong',
    'Kangpokpi',
    'Noney',
    'Pherzawl',
    'Senapati',
    'Tamenglong',
    'Tengnoupal',
    'Thoubal',
    'Ukhrul',
  ],
  'Mizoram': [
    'Aizawl',
    'Champhai',
    'Hnahthial',
    'Khawzawl',
    'Kolasib',
    'Lawngtlai',
    'Lunglei',
    'Mamit',
    'Saitual',
    'Siaha',
    'Vaitawng',
  ],
  'Nagaland': [
    'Chümoukedima',
    'Dimapur',
    'Kiphire',
    'Kohima',
    'Longleng',
    'Mokokchung',
    'Mon',
    'Niuland',
    'Noklak',
    'Peren',
    'Phek',
    'Shamator',
    'Tseminyu',
    'Tuensang',
    'Wokha',
    'Zunheboto',
  ],
  'Sikkim': [
    'Gangtok (East Sikkim)',
    'Gyalshing (West Sikkim)',
    'Mangan (North Sikkim)',
    'Namchi (South Sikkim)',
    'Pakyong',
    'Soreng',
  ],
  'Tripura': [
    'Dhalai (Ambassa)',
    'Gomati (Udaipur)',
    'Khowai',
    'North Tripura (Dharmanagar)',
    'Sepahijala (Bishramganj)',
    'South Tripura (Belonia)',
    'Unakoti (Kailashahar)',
    'West Tripura (Agartala)',
  ],
  'Ladakh': [
    'Kargil',
    'Leh',
  ],
  'Andaman and Nicobar Islands': [
    'Nicobar (Car Nicobar)',
    'North and Middle Andaman (Mayabunder)',
    'South Andaman (Port Blair)',
  ],
  'Dadra and Nagar Haveli and Daman and Diu': [
    'Dadra and Nagar Haveli (Silvassa)',
    'Daman',
    'Diu',
  ],
  'Lakshadweep': [
    'Agatti',
    'Amini',
    'Andrott',
    'Bitra',
    'Chetlat',
    'Kadmat',
    'Kalpeni',
    'Kavaratti',
    'Kiltan',
    'Minicoy',
  ],
};

export const DEFAULT_DISTRICTS = [
  'Central District',
  'East District',
  'West District',
  'North District',
  'South District',
];

export function getDistrictsForState(stateName: string): string[] {
  if (!stateName) return DEFAULT_DISTRICTS;
  const foundKey = Object.keys(STATE_DISTRICTS_MAP).find(
    k => k.toLowerCase() === stateName.toLowerCase()
  );
  return foundKey ? STATE_DISTRICTS_MAP[foundKey] : DEFAULT_DISTRICTS;
}
