export const STATE_DISTRICTS_MAP: Record<string, string[]> = {
  'Telangana': [
    'Hyderabad',
    'Rangareddy',
    'Medchal-Malkajgiri',
    'Warangal',
    'Karimnagar',
    'Nizamabad',
    'Khammam',
    'Nalgonda',
    'Sangareddy',
    'Siddipet',
    'Mahabubnagar',
    'Peddapalli',
    'Kamareddy',
    'Mancherial',
    'Jagtial',
    'Suryapet',
    'Wanaparthy',
    'Nagarkurnool',
  ],
  'Andhra Pradesh': [
    'Visakhapatnam',
    'NTR (Vijayawada)',
    'Guntur',
    'Tirupati',
    'Chittoor',
    'SPSR Nellore',
    'Kakinada',
    'East Godavari (Rajamahendravaram)',
    'West Godavari (Bhimavaram)',
    'Kurnool',
    'Anantapur',
    'YSR Kadapa',
    'Eluru',
    'Vizianagaram',
    'Srikakulam',
    'Prakasam (Ongole)',
    'Anakapalli',
    'Nandyal',
  ],
  'Maharashtra': [
    'Mumbai City',
    'Mumbai Suburban',
    'Thane',
    'Pune',
    'Nagpur',
    'Nashik',
    'Chhatrapati Sambhajinagar (Aurangabad)',
    'Solapur',
    'Amravati',
    'Kolhapur',
    'Navi Mumbai',
    'Pimpri-Chinchwad',
    'Sangli',
    'Nanded',
    'Jalgaon',
    'Akola',
    'Latur',
    'Satara',
    'Ahmednagar (Ahilyanagar)',
  ],
  'Karnataka': [
    'Bengaluru Urban',
    'Bengaluru Rural',
    'Mysuru',
    'Dharwad (Hubballi)',
    'Dakshina Kannada (Mangaluru)',
    'Belagavi',
    'Kalaburagi',
    'Ballari',
    'Tumakuru',
    'Shivamogga',
    'Davanagere',
    'Udupi',
    'Hassan',
    'Vijayapura',
    'Mandya',
  ],
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Tiruchirappalli (Trichy)',
    'Salem',
    'Tiruppur',
    'Erode',
    'Vellore',
    'Tirunelveli',
    'Thoothukudi',
    'Kanchipuram',
    'Chengalpattu',
    'Thanjavur',
    'Dindigul',
    'Cuddalore',
  ],
  'Uttar Pradesh': [
    'Lucknow',
    'Kanpur Nagar',
    'Varanasi',
    'Agra',
    'Prayagraj (Allahabad)',
    'Gautam Buddha Nagar (Noida)',
    'Ghaziabad',
    'Meerut',
    'Gorakhpur',
    'Bareilly',
    'Aligarh',
    'Moradabad',
    'Mathura',
    'Ayodhya',
    'Jhansi',
    'Saharanpur',
  ],
  'Delhi': [
    'New Delhi',
    'South Delhi',
    'North Delhi',
    'East Delhi',
    'West Delhi',
    'Central Delhi',
    'North West Delhi',
    'South West Delhi',
    'Shahdara',
    'North East Delhi',
    'South East Delhi',
  ],
  'Gujarat': [
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Junagadh',
    'Gandhinagar',
    'Anand',
    'Navsari',
    'Bharuch',
    'Mehsana',
    'Kutch (Bhuj)',
    'Patan',
  ],
  'West Bengal': [
    'Kolkata',
    'Howrah',
    'North 24 Parganas',
    'South 24 Parganas',
    'Hooghly',
    'Darjeeling',
    'Jalpaiguri (Siliguri)',
    'Paschim Bardhaman (Durgapur)',
    'Murshidabad',
    'Nadia',
    'Malda',
    'Purba Medinipur',
  ],
  'Rajasthan': [
    'Jaipur',
    'Jodhpur',
    'Kota',
    'Bikaner',
    'Ajmer',
    'Udaipur',
    'Bhilwara',
    'Alwar',
    'Sikar',
    'Sri Ganganagar',
    'Bharatpur',
    'Chittorgarh',
    'Jhunjhunu',
  ],
  'Bihar': [
    'Patna',
    'Gaya',
    'Bhagalpur',
    'Muzaffarpur',
    'Purnia',
    'Darbhanga',
    'Nalanda (Bihar Sharif)',
    'Bhojpur (Arrah)',
    'Begusarai',
    'Katihar',
    'Samastipur',
    'Rohtas',
  ],
  'Kerala': [
    'Thiruvananthapuram',
    'Ernakulam (Kochi)',
    'Kozhikode',
    'Thrissur',
    'Kollam',
    'Palakkad',
    'Malappuram',
    'Kannur',
    'Alappuzha',
    'Kottayam',
    'Pathanamthitta',
    'Idukki',
    'Wayanad',
    'Kasaragod',
  ],
  'Punjab': [
    'Ludhiana',
    'Amritsar',
    'Jalandhar',
    'Patiala',
    'Bathinda',
    'SAS Nagar (Mohali)',
    'Pathankot',
    'Hoshiarpur',
    'Moga',
    'Firozpur',
  ],
  'Haryana': [
    'Gurugram',
    'Faridabad',
    'Panipat',
    'Ambala',
    'Karnal',
    'Hisar',
    'Rohtak',
    'Sonipat',
    'Panchkula',
    'Yamunanagar',
  ],
  'Madhya Pradesh': [
    'Bhopal',
    'Indore',
    'Gwalior',
    'Jabalpur',
    'Ujjain',
    'Sagar',
    'Dewas',
    'Satna',
    'Ratlam',
    'Rewa',
    'Chhindwara',
  ],
  'Assam': [
    'Kamrup Metropolitan (Guwahati)',
    'Cachar (Silchar)',
    'Dibrugarh',
    'Jorhat',
    'Nagaon',
    'Tinsukia',
    'Sonitpur (Tezpur)',
  ],
  'Chhattisgarh': [
    'Raipur',
    'Durg (Bhilai)',
    'Bilaspur',
    'Korba',
    'Rajnandgaon',
    'Bastar (Jagdalpur)',
  ],
  'Jharkhand': [
    'Ranchi',
    'East Singhbhum (Jamshedpur)',
    'Dhanbad',
    'Bokaro',
    'Hazaribagh',
    'Deoghar',
  ],
  'Odisha': [
    'Khurda (Bhubaneswar)',
    'Cuttack',
    'Sundargarh (Rourkela)',
    'Ganjam (Berhampur)',
    'Sambalpur',
    'Puri',
    'Balasore',
  ],
  'Uttarakhand': [
    'Dehradun',
    'Haridwar',
    'Nainital (Haldwani)',
    'Udham Singh Nagar (Rudrapur)',
    'Pauri Garhwal (Rishikesh)',
  ],
  'Goa': [
    'North Goa (Panaji)',
    'South Goa (Margao)',
  ],
  'Jammu and Kashmir': [
    'Srinagar',
    'Jammu',
    'Anantnag',
    'Baramulla',
    'Udhampur',
    'Kathua',
  ],
  'Himachal Pradesh': [
    'Shimla',
    'Kangra (Dharamshala)',
    'Mandi',
    'Solan',
    'Kullu',
  ],
  'Puducherry': [
    'Puducherry',
    'Karaikal',
    'Mahe',
    'Yanam',
  ],
  'Chandigarh': [
    'Chandigarh Central',
    'Chandigarh North',
    'Chandigarh South',
  ],
  'Arunachal Pradesh': [
    'Papum Pare (Itanagar)',
    'East Siang (Pasighat)',
  ],
  'Meghalaya': [
    'East Khasi Hills (Shillong)',
    'West Garo Hills (Tura)',
  ],
  'Manipur': [
    'Imphal East',
    'Imphal West',
    'Thoubal',
    'Churachandpur',
  ],
  'Mizoram': [
    'Aizawl',
    'Lunglei',
    'Champhai',
  ],
  'Nagaland': [
    'Kohima',
    'Dimapur',
    'Mokokchung',
  ],
  'Sikkim': [
    'Gangtok',
    'Namchi',
    'Mangan',
  ],
  'Tripura': [
    'West Tripura (Agartala)',
    'Gomati (Udaipur)',
  ],
  'Ladakh': [
    'Leh',
    'Kargil',
  ],
  'Andaman and Nicobar Islands': [
    'South Andaman (Port Blair)',
    'North and Middle Andaman',
    'Nicobar',
  ],
  'Dadra and Nagar Haveli and Daman and Diu': [
    'Daman',
    'Diu',
    'Silvassa',
  ],
  'Lakshadweep': [
    'Kavaratti',
    'Agatti',
  ],
};

export const DEFAULT_DISTRICTS = [
  'Central District',
  'East District',
  'West District',
  'North District',
  'South District',
];

export function getDistrictsForState(stateName: string): string[] {
  if (!stateName) return DEFAULT_DISTRICTS;
  const foundKey = Object.keys(STATE_DISTRICTS_MAP).find(
    k => k.toLowerCase() === stateName.toLowerCase()
  );
  return foundKey ? STATE_DISTRICTS_MAP[foundKey] : DEFAULT_DISTRICTS;
}
