/*
# Seed July 2026 schemes, notifications, and applications

1. Purpose
   - Replace the old/odd placeholder schemes with fresh, real July 2026 government schemes.
   - Populate the Alerts & Updates (notifications) feed with current, relevant alerts.
   - Create sample "My Applications" entries with up-to-date statuses for the existing user.

2. Data changes
   - TRUNCATE schemes (CASCADE) to remove all old schemes and any dependent
     notifications / applications / saved_schemes / application_documents rows.
     All these tables are currently empty, so no user data is lost.
   - INSERT 12 new July 2026 schemes across multiple categories with eligibility
     criteria and required documents. Several are marked featured for the home screen.
   - INSERT 6 notifications for the existing user
     (95122569-8412-4112-a4f0-fd0ad82472b0) referencing the new schemes,
     covering approvals, deadlines, document requests, and new launches.
   - INSERT 4 applications for the same user referencing the new schemes,
     with varied statuses (approved, in_review, submitted, draft) and progress steps.

3. Security
   - No schema or RLS changes. Existing policies remain in place:
     schemes are readable by any authenticated user; notifications and
     applications are owner-scoped via auth.uid() = user_id.

4. Notes
   - Scheme IDs are generated by gen_random_uuid(); notifications and
     applications reference schemes by subquery on name so the migration
     is deterministic regardless of generated UUIDs.
   - Idempotent: TRUNCATE + INSERT can be re-run safely.
*/

TRUNCATE schemes CASCADE;

INSERT INTO schemes (name, description, category, eligibility, documents_required, featured) VALUES
('PM Vishwakarma Yojana 2026', 'Recognition, skill training, toolkit and collateral-free loan up to Rs 3 lakh for traditional artisans and craftspeople.', 'Skills & Employment', jsonb_build_object('requirements', ARRAY['Traditional artisan/craftsperson','Indian citizen','Age 18+','No government employee in family']), ARRAY['Aadhaar Card','Bank Passbook','Mobile number'], true),
('PM-Kisan 19th Installment 2026', 'Direct income support of Rs 6,000/year to landholding farmer families. 19th installment disbursed July 2026.', 'Agriculture', jsonb_build_object('requirements', ARRAY['Landholding farmer','Indian citizen','Not an institutional landholder','e-KYC completed']), ARRAY['Aadhaar Card','Land Records','Bank Passbook'], true),
('Ayushman Bharat PMJAY 2026 Expansion', 'Health insurance cover of Rs 5 lakh per family per year, now expanded to cover all senior citizens aged 70+ regardless of income.', 'Healthcare', jsonb_build_object('requirements', ARRAY['Indian citizen','Family listed in SECC or aged 70+','No government employee in family']), ARRAY['Aadhaar Card','Ration Card','Address Proof'], true),
('PM Awas Yojana-Urban 2.0 2026', 'Affordable housing with interest subsidy up to Rs 2.67 lakh for EWS/LIG/MIG families in urban areas.', 'Housing', jsonb_build_object('requirements', ARRAY['Annual family income below Rs 18 lakh','No pucca house owned','First-time home buyer','Indian citizen']), ARRAY['Aadhaar Card','Income Certificate','Address Proof','Bank Passbook'], true),
('Sukanya Samriddhi Yojana 2026', 'Savings scheme for girl child with 8.2% interest rate and tax benefits under Sec 80C.', 'Social Security', jsonb_build_object('requirements', ARRAY['Girl child below 10 years','Indian citizen','Single account per girl','Minimum deposit Rs 250/year']), ARRAY['Birth Certificate','Aadhaar Card','Guardian ID'], false),
('National Scholarship Portal 2026-27', 'Fresh scholarships for post-matric students from minority, SC/ST, and OBC categories for academic year 2026-27.', 'Education', jsonb_build_object('requirements', ARRAY['Family income below Rs 4.5 lakh','Minimum 50% marks','Indian citizen','Studying at recognized institution']), ARRAY['Aadhaar Card','Income Certificate','Marksheet','Institution Certificate'], true),
('Stand-Up India 2026', 'Bank loans between Rs 10 lakh and Rs 1 crore for SC/ST and women entrepreneurs setting up greenfield enterprises.', 'Business & Startup', jsonb_build_object('requirements', ARRAY['SC/ST or woman entrepreneur','First-time borrower','Greenfield enterprise','Age 18+']), ARRAY['Aadhaar Card','Business Plan','Project Report','Bank Passbook'], true),
('PM Surya Ghar Muft Bijli Yojana 2026', 'Rooftop solar installation with up to 300 units of free electricity per month and 60% subsidy for households.', 'Environment', jsonb_build_object('requirements', ARRAY['Household with valid roof','Aadhaar-linked electricity connection','Indian citizen']), ARRAY['Aadhaar Card','Electricity Bill','Property Proof','Bank Passbook'], true),
('MUDRA Loan Shishu/Kishore/Tarun 2026', 'Collateral-free micro loans up to Rs 10 lakh for small businesses in manufacturing, trading, and services.', 'Finance', jsonb_build_object('requirements', ARRAY['Small business owner','Non-farming activity','Indian citizen','Age 18+']), ARRAY['Aadhaar Card','Business Registration','Bank Statement'], false),
('Post-Matric Scholarship for Students with Disabilities 2026', 'Financial assistance for students with benchmark disabilities pursuing post-matric studies.', 'Education', jsonb_build_object('requirements', ARRAY['40% or more benchmark disability','Family income below Rs 6 lakh','Indian citizen']), ARRAY['Disability Certificate','Income Certificate','Marksheet','Aadhaar Card'], false),
('Pradhan Mantri Laghu Vyapari Maan-Dhan Yojana 2026', 'Pension scheme for small traders and shopkeepers aged 18-40, providing Rs 3,000/month after age 60.', 'Social Security', jsonb_build_object('requirements', ARRAY['Age 18-40 years','Small trader/shopkeeper','Annual turnover below Rs 1.5 crore','Not an income taxpayer']), ARRAY['Aadhaar Card','Bank Passbook','GST/Self Declaration'], false),
('Skill India Digital Hub 2026', 'Free online skill training and certification in AI, cybersecurity, and digital marketing with job placement support.', 'Digital Infrastructure', jsonb_build_object('requirements', ARRAY['Age 18-45','Indian citizen','Basic digital literacy']), ARRAY['Aadhaar Card','Education Certificate','Mobile number'], true)
ON CONFLICT DO NOTHING;

INSERT INTO notifications (user_id, title, message, type, scheme_id, read, created_at)
SELECT '95122569-8412-4112-a4f0-fd0ad82472b0', v.title, v.message, v.type, s.id, v.read, v.created_at::timestamptz
FROM (VALUES
  ('PM-Kisan 19th Installment Credited', 'Rs 2,000 has been credited to your bank account as the 19th installment of PM-Kisan Samman Nidhi.', 'success', 'PM-Kisan 19th Installment 2026', false, '2026-07-22T09:30:00Z'),
  ('Application Approved', 'Your PM Vishwakarma Yojana application has been approved. Toolkit and loan details will follow within 7 days.', 'success', 'PM Vishwakarma Yojana 2026', false, '2026-07-20T14:10:00Z'),
  ('Document Verification Required', 'Please upload your Income Certificate to complete your National Scholarship Portal application.', 'warning', 'National Scholarship Portal 2026-27', false, '2026-07-19T11:00:00Z'),
  ('New Scheme Launched', 'PM Surya Ghar Muft Bijli Yojana is now open for applications. Get up to 300 units of free electricity with 60% subsidy.', 'info', 'PM Surya Ghar Muft Bijli Yojana 2026', true, '2026-07-16T10:00:00Z'),
  ('Application Under Review', 'Your Ayushman Bharat PMJAY application is now under verification. You will receive an update within 15 days.', 'info', 'Ayushman Bharat PMJAY 2026 Expansion', false, '2026-07-15T16:45:00Z'),
  ('Deadline Approaching', 'Your Stand-Up India loan application deadline is in 5 days. Complete the remaining steps to avoid rejection.', 'warning', 'Stand-Up India 2026', true, '2026-07-12T08:20:00Z')
) AS v(title, message, type, scheme_name, read, created_at)
JOIN schemes s ON s.name = v.scheme_name;

INSERT INTO applications (user_id, scheme_id, scheme_name, status, current_step, total_steps, submitted_at, updated_at)
SELECT '95122569-8412-4112-a4f0-fd0ad82472b0', s.id, v.scheme_name, v.status, v.current_step, v.total_steps, v.submitted_at::timestamptz, v.updated_at::timestamptz
FROM (VALUES
  ('PM Vishwakarma Yojana 2026', 'approved', 6, 6, '2026-07-05T10:00:00Z', '2026-07-20T14:10:00Z'),
  ('Ayushman Bharat PMJAY 2026 Expansion', 'submitted', 4, 6, '2026-07-10T14:30:00Z', '2026-07-15T16:45:00Z'),
  ('National Scholarship Portal 2026-27', 'draft', 2, 6, '2026-07-18T09:00:00Z', '2026-07-19T11:00:00Z'),
  ('Stand-Up India 2026', 'submitted', 5, 6, '2026-07-08T12:00:00Z', '2026-07-12T08:20:00Z')
) AS v(scheme_name, status, current_step, total_steps, submitted_at, updated_at)
JOIN schemes s ON s.name = v.scheme_name;

INSERT INTO application_documents (application_id, user_id, name, status, uploaded_at, updated_at)
SELECT a.id, '95122569-8412-4112-a4f0-fd0ad82472b0', v.doc_name, v.doc_status, v.uploaded_at::timestamptz, v.updated_at::timestamptz
FROM applications a
JOIN (VALUES
  ('PM Vishwakarma Yojana 2026', 'Aadhaar Card', 'verified', '2026-07-05T10:05:00Z', '2026-07-08T12:00:00Z'),
  ('PM Vishwakarma Yojana 2026', 'Bank Passbook', 'verified', '2026-07-05T10:06:00Z', '2026-07-08T12:00:00Z'),
  ('Ayushman Bharat PMJAY 2026 Expansion', 'Aadhaar Card', 'verified', '2026-07-10T14:35:00Z', '2026-07-12T10:00:00Z'),
  ('Ayushman Bharat PMJAY 2026 Expansion', 'Ration Card', 'pending', '2026-07-10T14:36:00Z', '2026-07-10T14:36:00Z'),
  ('National Scholarship Portal 2026-27', 'Aadhaar Card', 'verified', '2026-07-18T09:05:00Z', '2026-07-19T09:00:00Z'),
  ('National Scholarship Portal 2026-27', 'Income Certificate', 'not_uploaded', '2026-07-18T09:06:00Z', '2026-07-18T09:06:00Z'),
  ('Stand-Up India 2026', 'Aadhaar Card', 'verified', '2026-07-08T12:05:00Z', '2026-07-09T10:00:00Z'),
  ('Stand-Up India 2026', 'Business Plan', 'verified', '2026-07-08T12:06:00Z', '2026-07-09T10:00:00Z'),
  ('Stand-Up India 2026', 'Project Report', 'pending', '2026-07-08T12:07:00Z', '2026-07-08T12:07:00Z')
) AS v(scheme_name, doc_name, doc_status, uploaded_at, updated_at)
ON v.scheme_name = a.scheme_name;
